# BP_Heli: rescue helicopter (js/heli.js makeHeli). Color 0 = red (y 43 m loop), 1 = blue (lower loop, other way round).
# Flies like a helicopter: velocity steering with smooth accel/brake, heading lags the flight path, banks into turns,
# nose down when speeding up / up when braking, bobs while hovering. Patrol = a drifting ellipse (radius + height sway);
# now and then it circles something interesting (a person, the big spider), keeps clear of the other helicopter.
# Searchlight = a real spot light on the ground (no shadows): red follows the person being chased, blue sweeps.
# Rescue(Human): fly over him, spiral down (slower near the ground), hover, he boards (Boarded, hidden), climb out (Done).
target('/Game/Game/BP_Heli')
M = '/Engine/BasicShapes/'
comp('Body', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Sphere.Sphere'})
comp('Glass', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Sphere.Sphere'})
comp('Tail', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cylinder.Cylinder'})
comp('Fin', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cube.Cube'})
comp('SkidL', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cylinder.Cylinder'})
comp('SkidR', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cylinder.Cylinder'})
comp('Hub', '/Script/Engine.SceneComponent')
comp('Blade1', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cube.Cube'}, parent='Hub')
comp('Blade2', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cube.Cube'}, parent='Hub')
comp('TailHub', '/Script/Engine.SceneComponent')
comp('TBlade', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cube.Cube'}, parent='TailHub')
comp('Search', '/Script/Engine.SpotLightComponent', {'IntensityUnits': 'Candelas', 'Intensity': 4000.0, 'AttenuationRadius': 9000.0, 'OuterConeAngle': 14.0, 'InnerConeAngle': 9.0,
                                                    'CastShadows': False, 'LightColor': {'R': 255, 'G': 244, 'B': 222, 'A': 255}})
comp('Rotor', '/Script/Engine.AudioComponent', {'Sound': '/Game/Game/Sound/S_Rotor.S_Rotor', 'bAutoActivate': True})
comp('Beacon', '/Script/Engine.PointLightComponent', {'Intensity': 0.0, 'AttenuationRadius': 900.0})
for n, t in [('Color', 'int'), ('Ang', 'float'), ('Mode', 'int'), ('T', 'float'), ('Alt', 'float'), ('RX', 'float'), ('RY', 'float'),
             ('Dir', 'float'), ('Yaw', 'float'), ('Done', 'bool'), ('Busy', 'bool'),
             ('Vel', 'Vector'), ('Sep', 'Vector'), ('Pitch', 'float'), ('Roll', 'float'), ('PoiT', 'float'), ('OrbT', 'float'), ('OrbA', 'float'),
             ('Aim', 'Vector'), ('A0', 'float'), ('Phase', 'float'), ('Night', 'float')]:   # Night 0..1: set by BP_Keeper's Clock
    var(n, t)
objvar('Target', '/Game/Game/BP_Human.BP_Human_C')
objvar('Poi', '/Script/Engine.Actor')
objvar('Other', '/Script/Engine.Actor')
objvar('Spider', '/Game/Spider/BP_Tarantula.BP_Tarantula_C')
edit('Color')

# the DSL's (Utilities|IsValid x) is the exec macro: as a value it cuts the flow, so wrap it
fn('Valid', [('A', '/Script/Engine.Actor')], [('Ok', 'bool')])
dsl('Valid', '''
(fn Valid (A)
  (Utilities|IsValid A
    (:"Is Valid" (return true))
    (:"Is Not Valid" (return false))))
''')

# volume by distance to the player camera (sounds have no attenuation assets)
fn('CamVol', [('P', 'Vector'), ('Far', 'float')], [('V', 'float')])
dsl('CamVol', '''
(fn CamVol (P Far)
  (bind cm (Game|GetPlayerCameraManager :PlayerIndex 0))
  (bind cl (Camera|GetCameraLocation :self cm))
  (return (Math|Float|Clamp(Float) (- 1.0 (/ (Math|Vector|Distance(Vector) cl P) Far)) 0.0 1.0)))
''')

fn('Part', [('C', '/Script/Engine.SceneComponent'), ('L', 'Vector'), ('R', 'Rotator'), ('S', 'Vector')])
dsl('Part', '''
(fn Part (C L R S)
  (Transformation|SetRelativeTransform :self C :NewTransform (Math|Transform|MakeTransform :Location L :Rotation R :Scale S)))
''')

fn('Setup')
dsl('Setup', '''
(fn Setup ()
  (bind z (Math|Rotator|MakeRotator 0.0 0.0 0.0))
  (bind side (Math|Rotator|MakeRotator 0.0 90.0 0.0))
  (for c (Actor|GetComponentsByClass :self self :ComponentClass "/Script/Engine.PrimitiveComponent")
    (Collision|SetCollisionEnabled :self c :NewType "NoCollision"))
  (Part :C Body :L (Math|Vector|MakeVector 0.0 0.0 0.0) :R z :S (Math|Vector|MakeVector 6.0 2.6 2.5))
  (Part :C Glass :L (Math|Vector|MakeVector 180.0 0.0 30.0) :R z :S (Math|Vector|MakeVector 2.8 2.2 1.8))
  (Part :C Tail :L (Math|Vector|MakeVector -620.0 0.0 50.0) :R side :S (Math|Vector|MakeVector 0.45 0.45 6.5))
  (Part :C Fin :L (Math|Vector|MakeVector -940.0 0.0 150.0) :R z :S (Math|Vector|MakeVector 0.9 0.1 1.8))
  (Part :C SkidL :L (Math|Vector|MakeVector 0.0 -120.0 -170.0) :R side :S (Math|Vector|MakeVector 0.12 0.12 5.0))
  (Part :C SkidR :L (Math|Vector|MakeVector 0.0 120.0 -170.0) :R side :S (Math|Vector|MakeVector 0.12 0.12 5.0))
  (Part :C Hub :L (Math|Vector|MakeVector 0.0 0.0 150.0) :R z :S (Math|Vector|MakeVector 1.0 1.0 1.0))
  (Part :C Blade1 :L (Math|Vector|MakeVector 0.0 0.0 0.0) :R z :S (Math|Vector|MakeVector 12.0 0.35 0.06))
  (Part :C Blade2 :L (Math|Vector|MakeVector 0.0 0.0 0.0) :R z :S (Math|Vector|MakeVector 0.35 12.0 0.06))
  (Part :C TailHub :L (Math|Vector|MakeVector -950.0 25.0 150.0) :R z :S (Math|Vector|MakeVector 1.0 1.0 1.0))
  (Part :C TBlade :L (Math|Vector|MakeVector 0.0 0.0 0.0) :R z :S (Math|Vector|MakeVector 2.2 0.05 0.25))
  (Part :C Search :L (Math|Vector|MakeVector 250.0 0.0 -180.0) :R (Math|Rotator|MakeRotator 0.0 -70.0 0.0) :S (Math|Vector|MakeVector 1.0 1.0 1.0))
  (Part :C Beacon :L (Math|Vector|MakeVector 0.0 0.0 -260.0) :R z :S (Math|Vector|MakeVector 1.0 1.0 1.0))
  (bind red (== Color 0))
  (if red
      (Rendering|Material|SetMaterial :self Body :ElementIndex 0 :Material "/Game/Game/Mat/MI_HeliRed.MI_HeliRed")
      (Rendering|Material|SetMaterial :self Tail :ElementIndex 0 :Material "/Game/Game/Mat/MI_HeliRed.MI_HeliRed")
      (Rendering|Material|SetMaterial :self Fin :ElementIndex 0 :Material "/Game/Game/Mat/MI_HeliRed.MI_HeliRed")
    (else
        (Rendering|Material|SetMaterial :self Body :ElementIndex 0 :Material "/Game/Game/Mat/MI_HeliBlue.MI_HeliBlue")
        (Rendering|Material|SetMaterial :self Tail :ElementIndex 0 :Material "/Game/Game/Mat/MI_HeliBlue.MI_HeliBlue")
        (Rendering|Material|SetMaterial :self Fin :ElementIndex 0 :Material "/Game/Game/Mat/MI_HeliBlue.MI_HeliBlue")))
  (Rendering|Material|SetMaterial :self Glass :ElementIndex 0 :Material "/Game/Game/Mat/MI_Glass.MI_Glass")
  (Rendering|Material|SetMaterial :self SkidL :ElementIndex 0 :Material "/Game/Game/Mat/MI_Black.MI_Black")
  (Rendering|Material|SetMaterial :self SkidR :ElementIndex 0 :Material "/Game/Game/Mat/MI_Black.MI_Black")
  (Rendering|Material|SetMaterial :self Blade1 :ElementIndex 0 :Material "/Game/Game/Mat/MI_Black.MI_Black")
  (Rendering|Material|SetMaterial :self Blade2 :ElementIndex 0 :Material "/Game/Game/Mat/MI_Black.MI_Black")
  (Rendering|Material|SetMaterial :self TBlade :ElementIndex 0 :Material "/Game/Game/Mat/MI_Black.MI_Black")
  (Rendering|Components|Light|SetLightColor :self Beacon :NewLightColor (select red (Math|Color|MakeColor 1.0 0.1 0.05 1.0) (Math|Color|MakeColor 0.2 0.4 1.0 1.0)))
  (Variables|Default|SetAlt (select red 4300.0 3300.0))
  (Variables|Default|SetRX (select red 4600.0 3800.0))
  (Variables|Default|SetRY (select red 2700.0 2200.0))
  (Variables|Default|SetDir (select red 1.0 -1.0))
  (Variables|Default|SetAng (select red 0.0 3.1))
  (Variables|Default|SetPhase (select red 0.0 2.0))
  (Variables|Default|SetPoiT (Math|Random|RandomFloatinRange 15.0 30.0))
  (Variables|Default|SetAim (- (Transformation|GetActorLocation) (Math|Vector|MakeVector 0.0 0.0 4000.0))))
''')

fn('Rescue', [('Who', '/Game/Game/BP_Human.BP_Human_C')])

# steer toward P at up to Spd (cm/s): velocity eases in/out, yaw follows the path with lag, bank = atan(v * turn rate / g),
# pitch = -atan(forward accel / g) - a little for cruise speed; keeps 32 m from the other helicopter; bobs when slow
fn('Fly', [('P', 'Vector'), ('Spd', 'float'), ('DT', 'float')], [('Arrived', 'bool')])
dsl('Fly', '''
(fn Fly (P Spd DT)
  (bind here (Transformation|GetActorLocation))
  (bind d (- P here))
  (bind len (Math|Vector|VectorLength d))
  (bind want (* (Math|Vector|Normalize d) (Math|Float|Min(Float) Spd (* len 0.45))))
  (Variables|Default|SetSep (Math|Vector|MakeVector 0.0 0.0 0.0))
  (if (Valid :A Other)
    (bind od (- here (Transformation|GetActorLocation :self Other)))
    (bind ol (Math|Vector|VectorLength od))
    (if (< ol 3200.0)
      (Variables|Default|SetSep (* (Math|Vector|Normalize od) (* (- 3200.0 ol) 0.7)))))
  (bind nv (Math|Interpolation|VInterpTo Vel (+ want Sep) DT 0.7))
  (bind hs0 (Math|Vector|VectorLength (Math|Vector|MakeVector (.x Vel) (.y Vel) 0.0)))
  (bind hs (Math|Vector|VectorLength (Math|Vector|MakeVector (.x nv) (.y nv) 0.0)))
  (bind acc (/ (- hs hs0) (Math|Float|Max(Float) DT 0.001)))
  (Variables|Default|SetVel nv)
  (bind hdg (select (> hs 150.0) (Math|Trig|Atan2(Degrees) (.y nv) (.x nv)) Yaw))
  (bind dy (* (Math|Float|Clamp(Float) (* (Math|Rotator|NormalizeAxis (- hdg Yaw)) 0.9) -30.0 30.0) DT))
  (Variables|Default|SetYaw (+ Yaw dy))
  (bind rate (Math|Trig|DegreesToRadians (/ dy (Math|Float|Max(Float) DT 0.001))))
  (bind bank (Math|Float|Clamp(Float) (* (Math|Trig|Atan2(Degrees) (* hs rate) 980.0) 1.4) -24.0 24.0))
  (bind pit (Math|Float|Clamp(Float) (- (* (Math|Trig|Atan2(Degrees) acc 980.0) -1.6) (* hs 0.006)) -16.0 12.0))
  (Variables|Default|SetRoll (Math|Interpolation|FInterpTo Roll bank DT 2.0))
  (Variables|Default|SetPitch (Math|Interpolation|FInterpTo Pitch pit DT 2.0))
  (bind bob (* (Math|Float|Clamp(Float) (- 1.0 (/ hs 300.0)) 0.0 1.0) (* 22.0 (Math|Trig|Sin(Radians) (* T 1.3)))))
  (Transformation|SetActorLocationAndRotation :self self :NewLocation (+ (+ here (* nv DT)) (Math|Vector|MakeVector 0.0 0.0 (* bob DT)))
     :NewRotation (Math|Rotator|MakeRotator Roll Pitch Yaw))
  (return (< len 120.0)))
''')

# searchlight: a ground point, eased; red onto the person the spider is chasing, a circled thing, straight down on a rescue, else a slow sweep
fn('Light', [('DT', 'float')])
dsl('Light', '''
(fn Light (DT)
  (bind here (Transformation|GetActorLocation))
  (bind fwd (Math|Vector|MakeVector (Math|Trig|Cos(Degrees) Yaw) (Math|Trig|Sin(Degrees) Yaw) 0.0))
  (bind right (Math|Vector|MakeVector (- 0.0 (Math|Trig|Sin(Degrees) Yaw)) (Math|Trig|Cos(Degrees) Yaw) 0.0))
  (bind sweep (+ (+ here (* fwd 1600.0)) (* right (* 1700.0 (Math|Trig|Sin(Radians) (* T 0.45))))))
  (Variables|Default|SetA0 0.0)
  (if (and (== Color 0) (Valid :A Spider))
    (bind vic (Class|BPTarantula|GetVictim :self Spider))
    (if (and (Valid :A vic) (> (Class|BPTarantula|GetChaseT :self Spider) 0.0))
      (Variables|Default|SetA0 1.0)
      (Variables|Default|SetAim (Math|Interpolation|VInterpTo Aim (Transformation|GetActorLocation :self vic) DT 3.0))))
  (if (and (== A0 0.0) (and (== Mode 5) (Valid :A Poi)))
    (Variables|Default|SetA0 1.0)
    (Variables|Default|SetAim (Math|Interpolation|VInterpTo Aim (Transformation|GetActorLocation :self Poi) DT 2.0)))
  (if (and (== A0 0.0) (and (>= Mode 2) (<= Mode 3)))
    (Variables|Default|SetA0 1.0)
    (Variables|Default|SetAim (Math|Interpolation|VInterpTo Aim (- here (Math|Vector|MakeVector 0.0 0.0 3000.0)) DT 2.0)))
  (if (== A0 0.0)
    (Variables|Default|SetAim (Math|Interpolation|VInterpTo Aim (Math|Vector|MakeVector (.x sweep) (.y sweep) 100.0) DT 1.2)))
  (bind d (- Aim (- here (Math|Vector|MakeVector 0.0 0.0 180.0))))
  (Rendering|Components|Light|SetIntensity :self Search :NewIntensity (Math|Float|Lerp 4000.0 35000.0 Night))
  (Transformation|SetWorldRotation :self Search :NewRotation (Math|Rotator|MakeRotator 0.0
     (Math|Trig|Atan2(Degrees) (.z d) (Math|Vector|VectorLength (Math|Vector|MakeVector (.x d) (.y d) 0.0))) (Math|Trig|Atan2(Degrees) (.y d) (.x d)))))
''')

# every 25-45 s on patrol: maybe circle a person (or the spider once it is big) for 14 s
fn('PickPoi')
dsl('PickPoi', '''
(fn PickPoi ()
  (Variables|Default|SetPoiT (Math|Random|RandomFloatinRange 25.0 45.0))
  (bind hs (Actor|GetAllActorsOfClass :ActorClass "/Game/Game/BP_Human.BP_Human_C"))
  (bind n (Utilities|Array|Length hs))
  (if (and (> n 0) (< (Math|Random|RandomFloat) 0.7))
    (Variables|Default|SetPoi (Utilities|Array|Get(acopy) hs (Math|Float|Truncate (* (Math|Random|RandomFloat) (* n 0.999)))))
    (Variables|Default|SetOrbT 14.0)
    (Variables|Default|SetMode 5)
    (return))
  (if (and (Valid :A Spider) (< (Math|Random|RandomFloat) 0.6))
    (if (>= (Class|BPTarantula|GetSpan :self Spider) 1200.0)
      (Variables|Default|SetPoi Spider)
      (Variables|Default|SetOrbT 14.0)
      (Variables|Default|SetMode 5))))
''')

# patrol point on the drifting ellipse, a bit ahead of Ang (the carrot the helicopter chases)
fn('Patrol', [('DT', 'float')])
dsl('Patrol', '''
(fn Patrol (DT)
  (Variables|Default|SetPoiT (- PoiT DT))
  (bind w (+ 0.09 (* 0.03 (Math|Trig|Sin(Radians) (+ (* T 0.05) Phase)))))
  (Variables|Default|SetAng (+ Ang (* (* Dir w) DT)))
  (bind la (+ Ang (* Dir 0.4)))
  (bind rk (+ 1.0 (* 0.16 (Math|Trig|Sin(Radians) (+ (* T 0.07) Phase)))))
  (bind alt (Math|Float|Min(Float) 5000.0 (+ (+ Alt (* 350.0 (Math|Trig|Sin(Radians) (+ (* T 0.11) Phase)))) 0.0)))
  (bind p (Math|Vector|MakeVector (* (* RX rk) (Math|Trig|Cos(Radians) la)) (* (* RY (- 2.0 rk)) (Math|Trig|Sin(Radians) la)) alt))
  (bind a (Fly :P p :Spd 750.0 :DT DT))
  (if (<= PoiT 0.0) (PickPoi)))
''')

# circle Poi at 19 m for OrbT s, then back onto the ellipse where it is now
fn('Orbit', [('DT', 'float')])
dsl('Orbit', '''
(fn Orbit (DT)
  (bind here (Transformation|GetActorLocation))
  (Variables|Default|SetOrbT (- OrbT DT))
  (if (or (<= OrbT 0.0) (not (Valid :A Poi)))
    (Variables|Default|SetMode 0)
    (Variables|Default|SetAng (Math|Trig|DegreesToRadians (Math|Trig|Atan2(Degrees) (/ (.y here) RY) (/ (.x here) RX))))
    (return))
  (Variables|Default|SetOrbA (+ OrbA (* (* Dir 0.3) DT)))
  (bind pp (Transformation|GetActorLocation :self Poi))
  (bind a (Fly :P (Math|Vector|MakeVector (+ (.x pp) (* 1900.0 (Math|Trig|Cos(Radians) OrbA))) (+ (.y pp) (* 1900.0 (Math|Trig|Sin(Radians) OrbA)))
                (Math|Float|Max(Float) 2700.0 (- Alt 700.0))) :Spd 650.0 :DT DT)))
''')

# rescue: 1 over him at cruise height, 2 spiral down 10 s (radius 9 m -> 0, slower near the ground), 3 hover 2.5 s + board, 4 climb out
fn('RescueTick', [('DT', 'float')])
dsl('RescueTick', '''
(fn RescueTick (DT)
  (bind here (Transformation|GetActorLocation))
  (bind tv (Valid :A Target))
  (if (and (and (>= Mode 1) (<= Mode 2)) (not tv))
    (Variables|Default|SetMode 4)
    (Variables|Default|SetT 0.0))
  (if (== Mode 1)
    (bind tp (Transformation|GetActorLocation :self Target))
    (if (Fly :P (Math|Vector|MakeVector (.x tp) (.y tp) Alt) :Spd 1000.0 :DT DT)
      (Variables|Default|SetMode 2)
      (Variables|Default|SetA0 (.z here))
      (Variables|Default|SetT 0.0))
    (return))
  (if (== Mode 2)
    (bind tp2 (Transformation|GetActorLocation :self Target))
    (bind u (Math|Float|Clamp(Float) (/ T 10.0) 0.0 1.0))
    (bind e (- 1.0 (* (- 1.0 u) (- 1.0 u))))
    (bind r (* 900.0 (- 1.0 e)))
    (bind sa (* T 0.8))
    (bind a2 (Fly :P (Math|Vector|MakeVector (+ (.x tp2) (* r (Math|Trig|Cos(Radians) sa))) (+ (.y tp2) (* r (Math|Trig|Sin(Radians) sa)))
                     (Math|Float|Lerp (Math|Float|Max(Float) A0 (+ (.z tp2) 600.0)) (+ (.z tp2) 480.0) e)) :Spd (Math|Float|Lerp 700.0 160.0 e) :DT DT))
    (if (and (>= u 1.0) (< (Math|Vector|Distance(Vector) here (+ tp2 (Math|Vector|MakeVector 0.0 0.0 480.0))) 250.0))
      (Variables|Default|SetMode 3)
      (Variables|Default|SetT 0.0))
    (return))
  (if (== Mode 3)
    (if tv
      (bind a3 (Fly :P (+ (Transformation|GetActorLocation :self Target) (Math|Vector|MakeVector 0.0 0.0 480.0)) :Spd 120.0 :DT DT))
      (else (bind a3b (Fly :P here :Spd 120.0 :DT DT))))
    (if (> T 2.5)
      (if tv
        (Class|BPHuman|SetBoarded :self Target :Boarded true)
        (Rendering|SetActorHiddenInGame :self Target :bNewHidden true))
      (Variables|Default|SetMode 4)
      (Variables|Default|SetT 0.0))
    (return))
  (if (== Mode 4)
    (bind fw (Math|Vector|MakeVector (Math|Trig|Cos(Degrees) Yaw) (Math|Trig|Sin(Degrees) Yaw) 0.0))
    (bind a4 (Fly :P (+ here (+ (* fw (* 900.0 (Math|Float|Clamp(Float) (/ T 3.0) 0.0 1.0))) (Math|Vector|MakeVector 0.0 0.0 (+ 300.0 (* T 120.0))))) :Spd 900.0 :DT DT))
    (if (> (.z here) 8000.0)
      (Variables|Default|SetDone true)
      (Rendering|SetActorHiddenInGame :self self :bNewHidden true))))
''')

dsl('EventGraph', '''
(event EventBeginPlay
  (Setup)
  (Variables|Default|SetSpider (Actor|GetActorOfClass :ActorClass "/Game/Spider/BP_Tarantula.BP_Tarantula_C")))
(event EventTick (DeltaSeconds)
  (bind dt (Math|Float|Min(Float) DeltaSeconds 0.05))
  (Variables|Default|SetT (+ T dt))
  (bind here0 (Transformation|GetActorLocation))
  (if (not (Valid :A Other))
    (for h (Actor|GetAllActorsOfClass :ActorClass "/Game/Game/BP_Heli.BP_Heli_C")
      (if (> (Math|Vector|Distance(Vector) (Transformation|GetActorLocation :self h) here0) 1.0) (Variables|Default|SetOther h))))
  (Class|AudioComponent|SetVolumeMultiplier :self Rotor :VolumeMultiplier (* 0.8 (CamVol :P here0 :Far 16000.0)))
  (Transformation|AddLocalRotation :self Hub :DeltaRotation (Math|Rotator|MakeRotator 0.0 0.0 (* 1300.0 dt)))
  (Transformation|AddLocalRotation :self TailHub :DeltaRotation (Math|Rotator|MakeRotator 0.0 (* 2000.0 dt) 0.0))
  (Rendering|Components|Light|SetIntensity :self Beacon :NewIntensity (select (< (Math|Float|%(Float) T 1.0) 0.12) 60000.0 0.0))
  (if (== Mode 0) (Patrol :DT dt))
  (if (== Mode 5) (Orbit :DT dt))
  (if (and (>= Mode 1) (<= Mode 4)) (RescueTick :DT dt))
  (Light :DT dt))
''')
dsl('Rescue', '''
(fn Rescue (Who)
  (Variables|Default|SetTarget Who)
  (Variables|Default|SetBusy true)
  (Variables|Default|SetMode 1))
''')
compile()
