# BP_Heli: rescue helicopter (js/heli.js makeHeli). Color 0 = red (y 43 m loop), 1 = blue (lower loop, other way round).
# Patrol an ellipse over the town with a searchlight + blinking beacon; Rescue(Human): fly over him, descend, hover,
# he boards (Boarded, hidden), then climb out of the tank (Done).
target('/Game/Game/BP_Heli')
M = '/Engine/BasicShapes/'
comp('Body', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Sphere.Sphere'})
comp('Glass', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Sphere.Sphere'})
comp('Tail', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cylinder.Cylinder'})
comp('Fin', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cube.Cube'})
comp('SkidL', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cylinder.Cylinder'})
comp('SkidR', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cylinder.Cylinder'})
comp('Hub', '/Script/Engine.SceneComponent')
comp('Blade1', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cube.Cube'}, parent='Hub')
comp('Blade2', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cube.Cube'}, parent='Hub')
comp('TailHub', '/Script/Engine.SceneComponent')
comp('TBlade', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cube.Cube'}, parent='TailHub')
comp('Search', '/Script/Engine.SpotLightComponent', {'Intensity': 200000.0, 'AttenuationRadius': 9000.0, 'OuterConeAngle': 16.0, 'InnerConeAngle': 8.0})
comp('Rotor', '/Script/Engine.AudioComponent', {'Sound': '/Game/Game/Sound/S_Rotor.S_Rotor', 'bAutoActivate': True})
comp('Beacon', '/Script/Engine.PointLightComponent', {'Intensity': 0.0, 'AttenuationRadius': 900.0})
for n, t in [('Color', 'int'), ('Ang', 'float'), ('Mode', 'int'), ('T', 'float'), ('Alt', 'float'), ('RX', 'float'), ('RY', 'float'),
             ('Dir', 'float'), ('Yaw', 'float'), ('Done', 'bool'), ('Busy', 'bool')]:
    var(n, t)
objvar('Target', '/Game/Game/BP_Human.BP_Human_C')
edit('Color')

# the DSL's (Utilities|IsValid x) is the exec macro: as a value it cuts the flow, so wrap it
fn('Valid', [('A', '/Script/Engine.Actor')], [('Ok', 'bool')])
dsl('Valid', '''
(fn Valid (A)
  (Utilities|IsValid A
    (:"Is Valid" (return true))
    (:"Is Not Valid" (return false))))
''')

# volume by distance to the player camera (sounds have no attenuation assets)
fn('CamVol', [('P', 'Vector'), ('Far', 'float')], [('V', 'float')])
dsl('CamVol', '''
(fn CamVol (P Far)
  (bind cm (Game|GetPlayerCameraManager :PlayerIndex 0))
  (bind cl (Camera|GetCameraLocation :self cm))
  (return (Math|Float|Clamp(Float) (- 1.0 (/ (Math|Vector|Distance(Vector) cl P) Far)) 0.0 1.0)))
''')

fn('Part', [('C', '/Script/Engine.SceneComponent'), ('L', 'Vector'), ('R', 'Rotator'), ('S', 'Vector')])
dsl('Part', '''
(fn Part (C L R S)
  (Transformation|SetRelativeTransform :self C :NewTransform (Math|Transform|MakeTransform :Location L :Rotation R :Scale S)))
''')

fn('Setup')
dsl('Setup', '''
(fn Setup ()
  (bind z (Math|Rotator|MakeRotator 0.0 0.0 0.0))
  (bind side (Math|Rotator|MakeRotator 0.0 90.0 0.0))
  (for c (Actor|GetComponentsByClass :self self :ComponentClass "/Script/Engine.PrimitiveComponent")
    (Collision|SetCollisionEnabled :self c :NewType "NoCollision"))
  (Part :C Body :L (Math|Vector|MakeVector 0.0 0.0 0.0) :R z :S (Math|Vector|MakeVector 6.0 2.6 2.5))
  (Part :C Glass :L (Math|Vector|MakeVector 180.0 0.0 30.0) :R z :S (Math|Vector|MakeVector 2.8 2.2 1.8))
  (Part :C Tail :L (Math|Vector|MakeVector -620.0 0.0 50.0) :R side :S (Math|Vector|MakeVector 0.45 0.45 6.5))
  (Part :C Fin :L (Math|Vector|MakeVector -940.0 0.0 150.0) :R z :S (Math|Vector|MakeVector 0.9 0.1 1.8))
  (Part :C SkidL :L (Math|Vector|MakeVector 0.0 -120.0 -170.0) :R side :S (Math|Vector|MakeVector 0.12 0.12 5.0))
  (Part :C SkidR :L (Math|Vector|MakeVector 0.0 120.0 -170.0) :R side :S (Math|Vector|MakeVector 0.12 0.12 5.0))
  (Part :C Hub :L (Math|Vector|MakeVector 0.0 0.0 150.0) :R z :S (Math|Vector|MakeVector 1.0 1.0 1.0))
  (Part :C Blade1 :L (Math|Vector|MakeVector 0.0 0.0 0.0) :R z :S (Math|Vector|MakeVector 12.0 0.35 0.06))
  (Part :C Blade2 :L (Math|Vector|MakeVector 0.0 0.0 0.0) :R z :S (Math|Vector|MakeVector 0.35 12.0 0.06))
  (Part :C TailHub :L (Math|Vector|MakeVector -950.0 25.0 150.0) :R z :S (Math|Vector|MakeVector 1.0 1.0 1.0))
  (Part :C TBlade :L (Math|Vector|MakeVector 0.0 0.0 0.0) :R z :S (Math|Vector|MakeVector 2.2 0.05 0.25))
  (Part :C Search :L (Math|Vector|MakeVector 250.0 0.0 -180.0) :R (Math|Rotator|MakeRotator 0.0 -70.0 0.0) :S (Math|Vector|MakeVector 1.0 1.0 1.0))
  (Part :C Beacon :L (Math|Vector|MakeVector 0.0 0.0 -260.0) :R z :S (Math|Vector|MakeVector 1.0 1.0 1.0))
  (bind red (== Color 0))
  (if red
      (Rendering|Material|SetMaterial :self Body :ElementIndex 0 :Material "/Game/Game/Mat/MI_HeliRed.MI_HeliRed")
      (Rendering|Material|SetMaterial :self Tail :ElementIndex 0 :Material "/Game/Game/Mat/MI_HeliRed.MI_HeliRed")
      (Rendering|Material|SetMaterial :self Fin :ElementIndex 0 :Material "/Game/Game/Mat/MI_HeliRed.MI_HeliRed")
    (else
        (Rendering|Material|SetMaterial :self Body :ElementIndex 0 :Material "/Game/Game/Mat/MI_HeliBlue.MI_HeliBlue")
        (Rendering|Material|SetMaterial :self Tail :ElementIndex 0 :Material "/Game/Game/Mat/MI_HeliBlue.MI_HeliBlue")
        (Rendering|Material|SetMaterial :self Fin :ElementIndex 0 :Material "/Game/Game/Mat/MI_HeliBlue.MI_HeliBlue")))
  (Rendering|Material|SetMaterial :self Glass :ElementIndex 0 :Material "/Game/Game/Mat/MI_Glass.MI_Glass")
  (Rendering|Material|SetMaterial :self SkidL :ElementIndex 0 :Material "/Game/Game/Mat/MI_Black.MI_Black")
  (Rendering|Material|SetMaterial :self SkidR :ElementIndex 0 :Material "/Game/Game/Mat/MI_Black.MI_Black")
  (Rendering|Material|SetMaterial :self Blade1 :ElementIndex 0 :Material "/Game/Game/Mat/MI_Black.MI_Black")
  (Rendering|Material|SetMaterial :self Blade2 :ElementIndex 0 :Material "/Game/Game/Mat/MI_Black.MI_Black")
  (Rendering|Material|SetMaterial :self TBlade :ElementIndex 0 :Material "/Game/Game/Mat/MI_Black.MI_Black")
  (Rendering|Components|Light|SetLightColor :self Beacon :NewLightColor (select red (Math|Color|MakeColor 1.0 0.1 0.05 1.0) (Math|Color|MakeColor 0.2 0.4 1.0 1.0)))
  (Variables|Default|SetAlt (select red 4300.0 3300.0))
  (Variables|Default|SetRX (select red 4600.0 3800.0))
  (Variables|Default|SetRY (select red 2700.0 2200.0))
  (Variables|Default|SetDir (select red 1.0 -1.0))
  (Variables|Default|SetAng (select red 0.0 3.1)))
''')

fn('Rescue', [('Who', '/Game/Game/BP_Human.BP_Human_C')])
fn('FlyTo', [('P', 'Vector'), ('Spd', 'float'), ('DT', 'float')], [('Arrived', 'bool')])
dsl('FlyTo', '''
(fn FlyTo (P Spd DT)
  (bind here (Transformation|GetActorLocation))
  (bind d (- P here))
  (bind len (Math|Vector|VectorLength d))
  (bind stepv (* (Math|Vector|Normalize d) (Math|Float|Min(Float) len (* Spd DT))))
  (if (> (Math|Vector|VectorLength (Math|Vector|MakeVector (.x d) (.y d) 0.0)) 50.0)
    (Variables|Default|SetYaw (Math|Interpolation|FInterpTo Yaw (+ Yaw (Math|Rotator|NormalizeAxis (- (Math|Trig|Atan2(Degrees) (.y d) (.x d)) Yaw))) DT 1.5)))
  (Transformation|SetActorLocationAndRotation :self self :NewLocation (+ here stepv)
     :NewRotation (Math|Rotator|MakeRotator 0.0 (Math|Float|Clamp(Float) (/ (* Spd -0.01) 1.0) -10.0 0.0) Yaw))
  (return (< len 60.0)))
''')

dsl('EventGraph', '''
(event EventBeginPlay
  (Setup))
(event EventTick (DeltaSeconds)
  (bind dt (Math|Float|Min(Float) DeltaSeconds 0.05))
  (Variables|Default|SetT (+ T dt))
  (bind here0 (Transformation|GetActorLocation))
  (Class|AudioComponent|SetVolumeMultiplier :self Rotor :VolumeMultiplier (* 0.8 (CamVol :P here0 :Far 16000.0)))
  (Transformation|AddLocalRotation :self Hub :DeltaRotation (Math|Rotator|MakeRotator 0.0 0.0 (* 1300.0 dt)))
  (Transformation|AddLocalRotation :self TailHub :DeltaRotation (Math|Rotator|MakeRotator 0.0 (* 2000.0 dt) 0.0))
  (Rendering|Components|Light|SetIntensity :self Beacon :NewIntensity (select (< (Math|Float|%(Float) T 1.0) 0.12) 60000.0 0.0))
  (if (== Mode 0)
    (Variables|Default|SetAng (+ Ang (* (* Dir 0.11) dt)))
    (bind p (Math|Vector|MakeVector (* RX (Math|Trig|Cos(Radians) Ang)) (* RY (Math|Trig|Sin(Radians) Ang)) (+ Alt (* 120.0 (Math|Trig|Sin(Radians) (* T 0.5))))))
    (bind a (FlyTo :P p :Spd 700.0 :DT dt)))
  (bind tv (Valid :A Target))
  (if (and (== Mode 1) tv)
    (bind tp (Transformation|GetActorLocation :self Target))
    (if (FlyTo :P (Math|Vector|MakeVector (.x tp) (.y tp) Alt) :Spd 1100.0 :DT dt)
      (Variables|Default|SetMode 2)))
  (if (and (== Mode 2) tv)
    (bind tp2 (Transformation|GetActorLocation :self Target))
    (if (FlyTo :P (+ tp2 (Math|Vector|MakeVector 0.0 0.0 480.0)) :Spd 380.0 :DT dt)
      (Variables|Default|SetMode 3)
      (Variables|Default|SetT 0.0)))
  (if (and (== Mode 3) (> T 2.5))
    (if tv
      (Class|BPHuman|SetBoarded :self Target :Boarded true)
      (Rendering|SetActorHiddenInGame :self Target :bNewHidden true))
    (Variables|Default|SetMode 4))
  (if (== Mode 4)
    (bind hp (Transformation|GetActorLocation))
    (if (FlyTo :P (Math|Vector|MakeVector (.x hp) (.y hp) 8000.0) :Spd 700.0 :DT dt)
      (Variables|Default|SetDone true)
      (Rendering|SetActorHiddenInGame :self self :bNewHidden true)))
  (if (and (and (>= Mode 1) (<= Mode 2)) (not tv))
    (Variables|Default|SetMode 4)))
''')
dsl('Rescue', '''
(fn Rescue (Who)
  (Variables|Default|SetTarget Who)
  (Variables|Default|SetBusy true)
  (Variables|Default|SetMode 1))
''')
compile()
