# BP_Human: ชัยภัทร (Who 0, 178 cm, red graduation gown) / ตุ้ย (Who 1, 170 cm, school shirt). Port of js/survive.js humanAI in short:
# hide at a wall -> trips to a store / the pond when hungry or thirsty (act 3.4 s) -> flee (sprint with stamina) when the spider
# is close or hunting him -> hide again. Body = primitives on pivots (hips/shoulders swing while walking, flail when held).
import json
SP = json.load(open('spots.json', encoding='utf-8'))   # hide / store / pond points (made from js/lots.js + ground traces)
target('/Game/Game/BP_Human')
M = '/Engine/BasicShapes/'
comp('Torso', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cylinder.Cylinder'})
comp('Gown', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cone.Cone'})
comp('Head', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Sphere.Sphere'})
comp('Hair', '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Sphere.Sphere'})
for s in ('L', 'R'):
    comp('Hip' + s, '/Script/Engine.SceneComponent')
    comp('Leg' + s, '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cylinder.Cylinder'}, parent='Hip' + s)
    comp('Sh' + s, '/Script/Engine.SceneComponent')
    comp('Arm' + s, '/Script/Engine.StaticMeshComponent', {'StaticMesh': M + 'Cylinder.Cylinder'}, parent='Sh' + s)
# speech bubble over the head (WBP_Bubble, bubble_ui.py): screen space, shown 4 s by Talk
comp('Bubble', '/Script/UMG.WidgetComponent', {'WidgetClass': '/Game/Game/WBP_Bubble.WBP_Bubble_C', 'Space': 'Screen', 'bDrawAtDesiredSize': True,
     'Pivot': {'x': 0.5, 'y': 1.0}, 'RelativeLocation': {'x': 0, 'y': 0, 'z': 235}, 'bVisible': False})
for n, t in [('Who', 'int'), ('Hs', 'float'), ('State', 'int'), ('StateT', 'float'), ('Target', 'Vector'), ('Speed', 'float'),
             ('Yaw', 'float'), ('Phase', 'float'), ('Stamina', 'float'), ('Food', 'float'), ('Water', 'float'), ('Held', 'bool'),
             ('Boarded', 'bool'), ('TripFood', 'bool'), ('LastP', 'Vector'), ('StuckT', 'float'), ('Best', 'float'), ('BestP', 'Vector'),
             ('SayT', 'float'), ('Still', 'bool'), ('Grief', 'float'), ('Name', 'string')]:
    var(n, t)
for n in ('Hides', 'Stores', 'Pond', 'Cur'): var(n, 'Vector', True)
objvar('Spider', '/Game/Spider/BP_Tarantula.BP_Tarantula_C')
objvar('Keeper', '/Game/Game/BP_Keeper.BP_Keeper_C')
objvar('NoWalk', '/Script/Engine.Actor', True)
edit('Who')

# the DSL's (Utilities|IsValid x) is the exec macro: as a value it cuts the flow, so wrap it
fn('Valid', [('A', '/Script/Engine.Actor')], [('Ok', 'bool')])
dsl('Valid', '''
(fn Valid (A)
  (Utilities|IsValid A
    (:"Is Valid" (return true))
    (:"Is Not Valid" (return false))))
''')

fn('GroundZ', [('P', 'Vector')], [('Z', 'float')])
dsl('GroundZ', '''
(fn GroundZ (P)
  (bind (hit ok) (Collision|LineTraceByChannel
     :Start (+ P (Math|Vector|MakeVector 0.0 0.0 800.0))
     :End (- P (Math|Vector|MakeVector 0.0 0.0 3000.0))
     :bTraceComplex true :ActorsToIgnore NoWalk))
  (if ok
    (bind (blk ovl tm dist loc imp) (Collision|BreakHitResult hit))
    (return (.z imp))
    (else (return (.z P)))))
''')

fn('Setup')
dsl('Setup', '''
(fn Setup ()
  (Variables|Default|SetHs (select (== Who 0) 1.0 0.955))
  (Variables|Default|SetName (select (== Who 0) "ชัยภัทร" "ตุ้ย"))
  (bind h Hs)
  (bind chai (== Who 0))
  (for c (Actor|GetComponentsByClass :self self :ComponentClass "/Script/Engine.PrimitiveComponent")
    (Collision|SetCollisionEnabled :self c :NewType "NoCollision"))
  (Transformation|SetRelativeTransform :self HipL :NewTransform (Math|Transform|MakeTransform :Location (Math|Vector|MakeVector 0.0 -9.0 (* 92.0 h))))
  (Transformation|SetRelativeTransform :self HipR :NewTransform (Math|Transform|MakeTransform :Location (Math|Vector|MakeVector 0.0 9.0 (* 92.0 h))))
  (Transformation|SetRelativeTransform :self ShL :NewTransform (Math|Transform|MakeTransform :Location (Math|Vector|MakeVector 0.0 -22.0 (* 146.0 h))))
  (Transformation|SetRelativeTransform :self ShR :NewTransform (Math|Transform|MakeTransform :Location (Math|Vector|MakeVector 0.0 22.0 (* 146.0 h))))
  (bind legT (Math|Transform|MakeTransform :Location (Math|Vector|MakeVector 0.0 0.0 (* -45.0 h)) :Scale (Math|Vector|MakeVector 0.14 0.14 (* 0.92 h))))
  (Transformation|SetRelativeTransform :self LegL :NewTransform legT)
  (Transformation|SetRelativeTransform :self LegR :NewTransform legT)
  (bind armT (Math|Transform|MakeTransform :Location (Math|Vector|MakeVector 0.0 0.0 (* -31.0 h)) :Scale (Math|Vector|MakeVector 0.09 0.09 (* 0.64 h))))
  (Transformation|SetRelativeTransform :self ArmL :NewTransform armT)
  (Transformation|SetRelativeTransform :self ArmR :NewTransform armT)
  (Transformation|SetRelativeTransform :self Torso :NewTransform (Math|Transform|MakeTransform :Location (Math|Vector|MakeVector 0.0 0.0 (* 122.0 h))
       :Scale (Math|Vector|MakeVector 0.24 (select chai 0.4 0.36) (* 0.6 h))))
  (Transformation|SetRelativeTransform :self Gown :NewTransform (Math|Transform|MakeTransform :Location (Math|Vector|MakeVector 0.0 0.0 (* 98.0 h))
       :Scale (Math|Vector|MakeVector 0.5 0.62 (* 1.08 h))))
  (Transformation|SetRelativeTransform :self Head :NewTransform (Math|Transform|MakeTransform :Location (Math|Vector|MakeVector 0.0 0.0 (* 165.0 h))
       :Scale (Math|Vector|MakeVector 0.21 0.19 0.24)))
  (Transformation|SetRelativeTransform :self Hair :NewTransform (Math|Transform|MakeTransform :Location (Math|Vector|MakeVector -2.0 0.0 (* 171.0 h))
       :Scale (Math|Vector|MakeVector 0.23 0.21 (select chai 0.17 0.2))))
  (Rendering|SetVisibility :self Gown :bNewVisibility chai)
  (Rendering|Material|SetMaterial :self Head :ElementIndex 0 :Material "/Game/Game/Mat/MI_Skin.MI_Skin")
  (Rendering|Material|SetMaterial :self Hair :ElementIndex 0 :Material "/Game/Game/Mat/MI_Hair.MI_Hair")
  (Rendering|Material|SetMaterial :self Gown :ElementIndex 0 :Material "/Game/Game/Mat/MI_Gown.MI_Gown")
  (if chai
    (Rendering|Material|SetMaterial :self Torso :ElementIndex 0 :Material "/Game/Game/Mat/MI_Gown.MI_Gown")
    (Rendering|Material|SetMaterial :self ArmL :ElementIndex 0 :Material "/Game/Game/Mat/MI_Gown.MI_Gown")
    (Rendering|Material|SetMaterial :self ArmR :ElementIndex 0 :Material "/Game/Game/Mat/MI_Gown.MI_Gown")
    (Rendering|Material|SetMaterial :self LegL :ElementIndex 0 :Material "/Game/Game/Mat/MI_Black.MI_Black")
    (Rendering|Material|SetMaterial :self LegR :ElementIndex 0 :Material "/Game/Game/Mat/MI_Black.MI_Black")
    (else
      (Rendering|Material|SetMaterial :self Torso :ElementIndex 0 :Material "/Game/Game/Mat/MI_School.MI_School")
      (Rendering|Material|SetMaterial :self ArmL :ElementIndex 0 :Material "/Game/Game/Mat/MI_Skin.MI_Skin")
      (Rendering|Material|SetMaterial :self ArmR :ElementIndex 0 :Material "/Game/Game/Mat/MI_Skin.MI_Skin")
      (Rendering|Material|SetMaterial :self LegL :ElementIndex 0 :Material "/Game/Game/Mat/MI_Navy.MI_Navy")
      (Rendering|Material|SetMaterial :self LegR :ElementIndex 0 :Material "/Game/Game/Mat/MI_Navy.MI_Navy"))))
''')

# walk cycle: legs / arms swing with Phase, bob; held = kick and wave
fn('Pose', [('DT', 'float')])
dsl('Pose', '''
(fn Pose (DT)
  (bind rate (select Held 3.0 (/ Speed (* 120.0 Hs))))
  (Variables|Default|SetPhase (+ Phase (* rate DT)))
  (bind amp (select Held 1.4 (Math|Float|Clamp(Float) (/ Speed 300.0) 0.0 1.0)))
  (bind s (Math|Trig|Sin(Radians) (* Phase 6.2832)))
  (bind lg (* (* s 38.0) amp))
  (bind ar (* (* s -30.0) amp))
  (bind up (select Held 150.0 0.0))
  (Transformation|SetRelativeRotation :self HipL :NewRotation (Math|Rotator|MakeRotator 0.0 lg 0.0))
  (Transformation|SetRelativeRotation :self HipR :NewRotation (Math|Rotator|MakeRotator 0.0 (- 0.0 lg) 0.0))
  (Transformation|SetRelativeRotation :self ShL :NewRotation (Math|Rotator|MakeRotator 0.0 (+ ar up) 0.0))
  (Transformation|SetRelativeRotation :self ShR :NewRotation (Math|Rotator|MakeRotator 0.0 (- up ar) 0.0)))
''')

# best spot of a list: far from the spider (Away) or near me (not Away), never within Fear of the spider
fn('Pick', [('L', 'int'), ('Away', 'bool'), ('Fear', 'float')], [('P', 'Vector')])
dsl('Pick', '''
(fn Pick (L Away Fear)
  (if (== L 0) (Variables|Default|SetCur Hides))
  (if (== L 1) (Variables|Default|SetCur Stores))
  (if (== L 2) (Variables|Default|SetCur Pond))
  (bind here (Transformation|GetActorLocation))
  (bind sp (Transformation|GetActorLocation :self Spider))
  (Variables|Default|SetBest -1000000000.0)
  (Variables|Default|SetBestP here)
  (for p Cur
    (bind dm (Math|Vector|Distance2D(Vector) p here))
    (bind ds (Math|Vector|Distance2D(Vector) p sp))
    (bind side (Math|Vector|DotProduct (Math|Vector|Normalize (- p here)) (Math|Vector|Normalize (- sp here))))
    (bind score (select Away (- (- ds (* dm 0.6)) (* side 1500.0)) (- (+ (* (Math|Random|RandomFloat) 1500.0) (* ds 0.2)) dm)))
    (if (and (> ds Fear) (> score Best))
      (Variables|Default|SetBest score)
      (Variables|Default|SetBestP p)))
  (return BestP))
''')

fn('ShowBubble', [('Msg', 'string')])
dsl('ShowBubble', '''
(fn ShowBubble (Msg)
  (Rendering|SetVisibility :self Bubble :bNewVisibility true)
  (Utilities|Casting|CastToWBP_Bubble :Object (UserInterface|GetWidget :self Bubble)
    (:then (Widget|SetText(Text) :self (Class|WBPBubble|GetTxt :self (Utilities|Casting|CastToWBP_Bubble :Object (UserInterface|GetWidget :self Bubble))) :InText (Utilities|Text|ToText(String) Msg)))
    (:CastFailed)))
''')

fn('Talk', [('Msg', 'string')])
dsl('Talk', '''
(fn Talk (Msg)
  (bind kv (Valid :A Keeper))
  (if (and (<= SayT 0.0) kv)
    (Class|BPKeeper|Log :self Keeper :Msg (Utilities|String|Append (Utilities|String|Append Name ": ") Msg))
    (ShowBubble :Msg Msg)
    (Variables|Default|SetSayT 6.0)))
''')

# brain: 0 hide (still), 1 flee, 2 trip to store/pond, 3 act (eat/drink), 4 wander to another hide spot
fn('Think', [('DT', 'float'), ('Days', 'float')])
dsl('Think', '''
(fn Think (DT Days)
  (Variables|Default|SetStateT (+ StateT DT))
  (Variables|Default|SetSayT (- SayT DT))
  (Variables|Default|SetGrief (- Grief DT))
  (Variables|Default|SetFood (Math|Float|Max(Float) 0.0 (- Food (/ Days 5.0))))
  (Variables|Default|SetWater (Math|Float|Max(Float) 0.0 (- Water (/ Days 3.5))))
  (bind here (Transformation|GetActorLocation))
  (bind sp (Transformation|GetActorLocation :self Spider))
  (bind span (Class|BPTarantula|GetSpan :self Spider))
  (bind dsp (Math|Vector|Distance2D(Vector) here sp))
  (bind hunted (and (Class|BPTarantula|GetHunting :self Spider) (== (Class|BPTarantula|GetVictim :self Spider) self)))
  (bind fear (+ 900.0 (* span 0.9)))
  (bind danger (or (< dsp fear) (and hunted (< dsp (* fear 2.2)))))
  (if (and danger (!= State 1))
    (Variables|Default|SetState 1) (Variables|Default|SetStateT 0.0)
    (Variables|Default|SetTarget (Pick :L 0 :Away true :Fear (* fear 0.8)))
    (Talk :Msg (select (== Who 0) "มันมาแล้ว!! วิ่ง!!" "ไม่ไหวแล้ว โค้ดชีวิตนี้มีบั๊ก!!")))
  (if (and (== State 1) (> StateT 1.2) (not danger))
    (Variables|Default|SetState 0) (Variables|Default|SetStateT 0.0)
    (Variables|Default|SetTarget (Pick :L 0 :Away false :Fear fear)))
  (if (and (== State 1) (> StateT 1.5) danger (< (Math|Vector|Distance2D(Vector) here Target) 150.0))
    (Variables|Default|SetStateT 0.0)
    (Variables|Default|SetTarget (Pick :L 0 :Away true :Fear (* fear 0.8))))
  (if (and (== State 0) (> StateT (Math|Random|RandomFloatinRange 6.0 12.0)) (<= Grief 0.0))
    (Variables|Default|SetStateT 0.0)
    (if (or (< Food 0.55) (< Water 0.55))
      (Variables|Default|SetState 2)
      (Variables|Default|SetTripFood (<= Food Water))
      (Variables|Default|SetTarget (Pick :L (select TripFood 1 2) :Away false :Fear fear))
      (Talk :Msg (select TripFood (select (== Who 0) "หิวแล้ว ไปหาข้าวปั้นที่ร้านดีกว่า" "ท้องร้องเป็นเสียง compile error")
                                  (select (== Who 0) "คอแห้ง ไปหาน้ำที่บ่อ" "ต้องการ H2O ด่วน")))
      (else
        (Variables|Default|SetState 4)
        (Variables|Default|SetTarget (Pick :L 0 :Away false :Fear fear)))))
  (if (and (or (== State 2) (== State 4)) (< (Math|Vector|Distance2D(Vector) here Target) 140.0))
    (Variables|Default|SetStateT 0.0)
    (Variables|Default|SetState (select (== State 2) 3 0)))
  (if (and (== State 3) (> StateT 3.4))
    (if TripFood (Variables|Default|SetFood 1.0) (else (Variables|Default|SetWater 1.0)))
    (Talk :Msg (select TripFood "อิ่มแล้ว กลับไปหลบก่อน" "ชื่นใจ... กลับไปหลบ"))
    (Variables|Default|SetState 0) (Variables|Default|SetStateT 0.0)
    (Variables|Default|SetTarget (Pick :L 0 :Away false :Fear fear))))
''')

fn('Move', [('DT', 'float')])
dsl('Move', '''
(fn Move (DT)
  (bind here (Transformation|GetActorLocation))
  (bind dist (Math|Vector|Distance2D(Vector) here Target))
  (bind flee (== State 1))
  (bind urgent (or (< Food 0.2) (< Water 0.2)))
  (bind sprint (and flee (> Stamina 0.05)))
  (Variables|Default|SetStamina (Math|Float|Clamp(Float) (+ Stamina (* DT (select sprint -0.18 0.08))) 0.0 1.0))
  (bind top (select flee (select sprint 950.0 480.0) (select (== State 2) (select urgent 320.0 150.0) 140.0)))
  (bind still (or (or (== State 3) (< dist 60.0)) (and (== State 0) (< dist 100.0))))
  (bind dx (- (.x Target) (.x here)))
  (bind dy (- (.y Target) (.y here)))
  (bind dYaw (Math|Rotator|NormalizeAxis (- (Math|Trig|Atan2(Degrees) dy dx) Yaw)))
  (bind turn (select flee 720.0 300.0))
  (if (not still) (Variables|Default|SetYaw (+ Yaw (Math|Float|Clamp(Float) dYaw (* turn (- 0.0 DT)) (* turn DT)))))
  (bind face (Math|Float|Clamp(Float) (/ (- (Math|Trig|Cos(Degrees) dYaw) 0.2) 0.8) 0.0 1.0))
  (bind want (select still 0.0 (* top face)))
  (Variables|Default|SetSpeed (Math|Interpolation|FInterpTo Speed want DT (select flee 8.0 4.0)))
  (bind fwd (Math|Vector|MakeVector (Math|Trig|Cos(Degrees) Yaw) (Math|Trig|Sin(Degrees) Yaw) 0.0))
  (bind np (+ here (* fwd (* Speed DT))))
  (bind g0 (GroundZ :P here))
  (bind g1 (GroundZ :P (+ here (* fwd 45.0))))
  (bind wall (> (- g1 g0) 60.0))
  (if wall (Variables|Default|SetYaw (+ Yaw (* (select (> dYaw 0.0) 1.0 -1.0) (* 400.0 DT)))))
  (bind np2 (select wall here np))
  (bind gz (GroundZ :P np2))
  (Variables|Default|SetStuckT (+ StuckT DT))
  (if (> StuckT 1.6)
    (if (and (not still) (< (Math|Vector|Distance2D(Vector) here LastP) 60.0))
      (Variables|Default|SetTarget (Pick :L 0 :Away flee :Fear 0.0)))
    (Variables|Default|SetStuckT 0.0)
    (Variables|Default|SetLastP here))
  (Transformation|SetActorLocationAndRotation :self self
     :NewLocation (Math|Vector|MakeVector (.x np2) (.y np2) (Math|Interpolation|FInterpTo (.z here) gz DT 14.0))
     :NewRotation (Math|Rotator|MakeRotator 0.0 0.0 Yaw)))
''')

dsl('EventGraph', '''
(event EventBeginPlay
  (Variables|Default|SetNoWalk (Actor|GetAllActorswithTag :Tag "NoWalk"))
  (Variables|Default|SetSpider (Actor|GetActorOfClass :ActorClass "/Game/Spider/BP_Tarantula.BP_Tarantula_C"))
  (Variables|Default|SetKeeper (Actor|GetActorOfClass :ActorClass "/Game/Game/BP_Keeper.BP_Keeper_C"))
  (Variables|Default|SetFood 1.0)
  (Variables|Default|SetWater 1.0)
  (Variables|Default|SetStamina 1.0)
  (Variables|Default|SetState 4)
  (Variables|Default|SetStateT 0.0)
  (Variables|Default|SetTarget (Transformation|GetActorLocation))
  (Setup))
(event EventTick (DeltaSeconds)
  (bind dt (Math|Float|Min(Float) DeltaSeconds 0.05))
  (Rendering|SetVisibility :self Bubble :bNewVisibility (> SayT 2.0))
  (if (and (not Held) (not Boarded))
    (Utilities|IsValid Spider
      (:"Is Valid"
        (Think :DT dt :Days (/ (* dt (Class|BPKeeper|GetTimeMul :self Keeper)) 12.0))
        (Move :DT dt)
        (Pose :DT dt)))
    (else (Pose :DT dt))))
''')
compile()
O = 'editor_toolset.toolsets.object.ObjectTools'
v = lambda L: [{'x': p[0], 'y': p[1], 'z': p[2] if p[2] is not None else 100} for p in L]
print('spots', call(O, 'set_properties', {'instance': {'refPath': '/Game/Game/BP_Human.Default__BP_Human_C'},
                                          'values': json.dumps({'Hides': v(SP['hides']), 'Stores': v(SP['stores']), 'Pond': v(SP['pond'])})}))
