# BP_Keeper: the player (game.js camera + buttons + tank climate + save). Orbit camera on a spring arm around Focus
# (RMB drag = turn, wheel = zoom, WASD = pan, F = follow the spider), keys/buttons: 1 cricket, 2 dubia, M mist, T time speed,
# H help. Clock: 1 real s = 0.5 h x TimeMul (same as BP_Tarantula Needs); sun follows the hour; humidity falls, mist raises it.
target('/Game/Game/BP_Keeper', '/Script/Engine.Pawn')
comp('Arm', '/Script/Engine.SpringArmComponent', {'bDoCollisionTest': False, 'TargetArmLength': 3800.0})
comp('Cam', '/Script/Engine.CameraComponent', {'FieldOfView': 55.0}, parent='Arm')
for n, t in [('Yaw', 'float'), ('Pitch', 'float'), ('Dist', 'float'), ('DistNow', 'float'), ('Focus', 'Vector'), ('Follow', 'bool'),
             ('Hours', 'float'), ('Day', 'int'), ('Hum', 'float'), ('Temp', 'float'), ('TimeMul', 'float'), ('SaveT', 'float'),
             ('MistT', 'float'), ('Notice', 'string'), ('NoticeT', 'float'), ('LogText', 'string'),
             ('LastMeals', 'int'), ('LastStage', 'int'), ('Found', 'bool'), ('SpawnP', 'Vector'),
             ('NL', 'string'), ('P1', 'bool'), ('P2', 'bool'), ('P3', 'bool'), ('P4', 'bool'), ('P5', 'bool'), ('P6', 'bool')]:
    var(n, t)
objvar('Spider', '/Game/Spider/BP_Tarantula.BP_Tarantula_C')
objvar('HUD', '/Game/Game/WBP_HUD.WBP_HUD_C')
objvar('SG', '/Game/Game/SG_Tarantula.SG_Tarantula_C')
objvar('Sun', '/Script/Engine.DirectionalLight')
objvar('Fog', '/Script/Engine.ExponentialHeightFog')

# "[HH:MM] text" on top of the log (kept short)
fn('Log', [('Msg', 'string')])
dsl('Log', '''
(fn Log (Msg)
  (bind h (Math|Float|Truncate Hours))
  (bind m (Math|Float|Truncate (* (- Hours h) 60.0)))
  (bind hh (Utilities|String|Append (select (< h 10) "0" "") (Utilities|String|ToString(Integer) h)))
  (bind mm (Utilities|String|Append (select (< m 10) "0" "") (Utilities|String|ToString(Integer) m)))
  (bind line (Utilities|String|Append (Utilities|String|Append (Utilities|String|Append "[" hh) (Utilities|String|Append ":" mm)) (Utilities|String|Append "] " Msg)))
  (Variables|Default|SetLogText (Utilities|String|Left (Utilities|String|Append (Utilities|String|Append line NL) LogText) 700)))
''')

fn('Say', [('Msg', 'string')])
dsl('Say', '''
(fn Say (Msg)
  (Variables|Default|SetNotice Msg)
  (Variables|Default|SetNoticeT 3.5))
''')

# release prey: max 4, never while molting / soft (live prey is dangerous then), away from the spider, not in the pond
fn('SpawnPrey', [('Kind', 'int')])
dsl('SpawnPrey', '''
(fn SpawnPrey (Kind)
  (bind all (Actor|GetAllActorsOfClass :ActorClass "/Game/Game/BP_Prey.BP_Prey_C"))
  (bind st (Class|BPTarantula|GetStage :self Spider))
  (if (>= (Utilities|Array|Length all) 4)
    (Say :Msg "ในตู้มีเหยื่อครบ 4 ตัวแล้ว")
    (elif (>= st 2)
      (Say :Msg "ห้ามให้อาหารตอนลอกคราบ/ตัวนิ่ม — เหยื่อเป็นอันตรายต่อแมงมุม")
      (else
        (bind span (Class|BPTarantula|GetSpan :self Spider))
        (bind sp (Transformation|GetActorLocation :self Spider))
        (Variables|Default|SetFound false)
        (for i (range 30)
          (bind p (Math|Vector|MakeVector (Math|Random|RandomFloatinRange -5200.0 1300.0) (Math|Random|RandomFloatinRange -700.0 3500.0) 600.0))
          (bind ok (and (> (Math|Vector|Distance2D(Vector) p sp) (+ (* span 2.5) 600.0)) (> (Math|Vector|Distance2D(Vector) p (Math|Vector|MakeVector 300.0 2550.0 0.0)) 850.0)))
          (if (and ok (not Found))
            (Variables|Default|SetFound true)
            (Variables|Default|SetSpawnP p)))
        (bind a (Game|SpawnActorfromClass :Class "/Game/Game/BP_Prey.BP_Prey_C"
                   :SpawnTransform (Math|Transform|MakeTransform :Location SpawnP) :CollisionHandlingOverride "AlwaysSpawn"))
        (Class|BPPrey|SetKind :self a :Kind Kind)
        (Class|BPPrey|SetK :self a :K (/ span 1200.0))
        (Class|BPPrey|Setup :self a)
        (if (== st 1) (Say :Msg "ช่วงก่อนลอกคราบ แมงมุมจะไม่กินอาหาร"))
        (Log :Msg (select (== Kind 0) "ปล่อยจิ้งหรีดลงตู้" "ปล่อยแมลงสาบดูเบียลงตู้"))))))
''')

fn('Mist')
dsl('Mist', '''
(fn Mist ()
  (Variables|Default|SetHum (Math|Float|Min(Float) 100.0 (+ Hum 30.0)))
  (Variables|Default|SetMistT 8.0)
  (Log :Msg (Utilities|String|Append "พ่นน้ำ ความชื้นเป็น " (Utilities|String|Append (Utilities|String|ToString(Integer) (Math|Float|Round Hum)) "%"))))
''')

fn('CycleSpeed')
dsl('CycleSpeed', '''
(fn CycleSpeed ()
  (Variables|Default|SetTimeMul (select (< TimeMul 5.0) 10.0 (select (< TimeMul 30.0) 60.0 1.0)))
  (Say :Msg (Utilities|String|Append "ความเร็วเวลา x" (Utilities|String|ToString(Integer) (Math|Float|Round TimeMul)))))
''')

fn('ToggleHelp')
dsl('ToggleHelp', '''
(fn ToggleHelp ()
  (bind box (Class|WBPHUD|GetHelpBox :self HUD))
  (bind vis (Widget|IsVisible :self box))
  (if vis
    (Widget|SetVisibility :self box :InVisibility "Collapsed")
    (else (Widget|SetVisibility :self box :InVisibility "Visible"))))
''')

fn('ToggleFollow')
dsl('ToggleFollow', '''
(fn ToggleFollow ()
  (Variables|Default|SetFollow (not Follow))
  (Say :Msg (select Follow "กล้องติดตามแมงมุม" "กล้องอิสระ")))
''')

# keyboard, mouse and the HUD buttons (buttons polled: fire when released)
fn('Controls', [('DT', 'float')])
dsl('Controls', '''
(fn Controls (DT)
  (bind pc (Game|GetPlayerController :PlayerIndex 0))
  (bind (mx my) (Game|Player|GetInputMouseDelta :self pc))
  (if (Game|Player|IsInputKeyDown :self pc :Key "RightMouseButton")
    (Variables|Default|SetYaw (+ Yaw (* mx 0.3)))
    (Variables|Default|SetPitch (Math|Float|Clamp(Float) (+ Pitch (* my 0.3)) -85.0 -4.0)))
  (if (Game|Player|WasInputKeyJustPressed :self pc :Key "MouseScrollUp") (Variables|Default|SetDist (Math|Float|Max(Float) 350.0 (* Dist 0.86))))
  (if (Game|Player|WasInputKeyJustPressed :self pc :Key "MouseScrollDown") (Variables|Default|SetDist (Math|Float|Min(Float) 11000.0 (* Dist 1.16))))
  (bind fwd (Math|Vector|MakeVector (Math|Trig|Cos(Degrees) Yaw) (Math|Trig|Sin(Degrees) Yaw) 0.0))
  (bind right (Math|Vector|MakeVector (- 0.0 (Math|Trig|Sin(Degrees) Yaw)) (Math|Trig|Cos(Degrees) Yaw) 0.0))
  (bind f (- (select (Game|Player|IsInputKeyDown :self pc :Key "W") 1.0 0.0) (select (Game|Player|IsInputKeyDown :self pc :Key "S") 1.0 0.0)))
  (bind r (- (select (Game|Player|IsInputKeyDown :self pc :Key "D") 1.0 0.0) (select (Game|Player|IsInputKeyDown :self pc :Key "A") 1.0 0.0)))
  (if (or (!= f 0.0) (!= r 0.0))
    (Variables|Default|SetFollow false)
    (bind mv (* (+ (* fwd f) (* right r)) (* (* Dist 0.7) DT)))
    (bind nf (+ Focus mv))
    (Variables|Default|SetFocus (Math|Vector|MakeVector (Math|Float|Clamp(Float) (.x nf) -6500.0 6500.0) (Math|Float|Clamp(Float) (.y nf) -4500.0 4500.0) (.z nf))))
  (bind b1 (Button|IsPressed :self (Class|WBPHUD|GetBtnCricket :self HUD)))
  (bind b2 (Button|IsPressed :self (Class|WBPHUD|GetBtnDubia :self HUD)))
  (bind b3 (Button|IsPressed :self (Class|WBPHUD|GetBtnMist :self HUD)))
  (bind b4 (Button|IsPressed :self (Class|WBPHUD|GetBtnFollow :self HUD)))
  (bind b5 (Button|IsPressed :self (Class|WBPHUD|GetBtnSpeed :self HUD)))
  (bind b6 (Button|IsPressed :self (Class|WBPHUD|GetBtnHelp :self HUD)))
  (if (or (Game|Player|WasInputKeyJustPressed :self pc :Key "One") (and P1 (not b1))) (SpawnPrey :Kind 0))
  (if (or (Game|Player|WasInputKeyJustPressed :self pc :Key "Two") (and P2 (not b2))) (SpawnPrey :Kind 1))
  (if (or (Game|Player|WasInputKeyJustPressed :self pc :Key "M") (and P3 (not b3))) (Mist))
  (if (or (Game|Player|WasInputKeyJustPressed :self pc :Key "F") (and P4 (not b4))) (ToggleFollow))
  (if (or (Game|Player|WasInputKeyJustPressed :self pc :Key "T") (and P5 (not b5))) (CycleSpeed))
  (if (or (Game|Player|WasInputKeyJustPressed :self pc :Key "H") (and P6 (not b6))) (ToggleHelp))
  (Variables|Default|SetP1 b1) (Variables|Default|SetP2 b2) (Variables|Default|SetP3 b3)
  (Variables|Default|SetP4 b4) (Variables|Default|SetP5 b5) (Variables|Default|SetP6 b6))
''')

fn('Camera', [('DT', 'float')])
dsl('Camera', '''
(fn Camera (DT)
  (if Follow
    (bind sp (Transformation|GetActorLocation :self Spider))
    (Variables|Default|SetFocus (Math|Interpolation|VInterpTo Focus sp DT 3.0)))
  (Variables|Default|SetDistNow (Math|Interpolation|FInterpTo DistNow Dist DT 6.0))
  (Transformation|SetActorLocation :self self :NewLocation Focus)
  (Transformation|SetWorldRotation :self Arm :NewRotation (Math|Rotator|MakeRotator 0.0 Pitch Yaw))
  (Class|SpringArmComponent|SetTargetArmLength :self Arm :TargetArmLength DistNow))
''')

# clock, sun, humidity, temperature, spider time scale, mist fog
fn('Clock', [('DT', 'float')])
dsl('Clock', '''
(fn Clock (DT)
  (bind hrs (* (* DT 0.5) TimeMul))
  (Class|BPTarantula|SetTimeScale :self Spider :TimeScale TimeMul)
  (bind nh (+ Hours hrs))
  (if (>= nh 24.0)
    (Variables|Default|SetDay (+ Day 1))
    (Log :Msg (Utilities|String|Append "เริ่มวันที่ " (Utilities|String|ToString(Integer) Day))))
  (Variables|Default|SetHours (select (>= nh 24.0) (- nh 24.0) nh))
  (Variables|Default|SetHum (Math|Float|Max(Float) 25.0 (- Hum (* hrs 1.1))))
  (bind s (Math|Trig|Sin(Radians) (* (/ (- Hours 6.0) 12.0) 3.1416)))
  (Variables|Default|SetTemp (+ 25.5 (* 3.0 s)))
  (Transformation|SetActorRotation :self Sun :NewRotation (Math|Rotator|MakeRotator 0.0 (- 0.0 (Math|Float|Max(Float) 10.0 (* 62.0 s))) (+ 30.0 (* Hours 4.0))) :bTeleportPhysics false)
  (bind lc (Actor|GetComponentbyClass :self Sun :ComponentClass "/Script/Engine.LightComponent"))
  (Rendering|Components|Light|SetIntensity :self lc :NewIntensity (Math|Float|Lerp 1.6 6.0 (Math|Float|Clamp(Float) (* s 2.5) 0.0 1.0)))
  (Variables|Default|SetMistT (Math|Float|Max(Float) 0.0 (- MistT DT)))
  (bind fc (Actor|GetComponentbyClass :self Fog :ComponentClass "/Script/Engine.ExponentialHeightFogComponent"))
  (Rendering|Components|ExponentialHeightFog|SetFogDensity :self fc :Value (+ 0.02 (* MistT 0.012))))
''')

fn('StageName', [('S', 'int')], [('N', 'string')])
dsl('StageName', '''
(fn StageName (S)
  (return (select (== S 0) "ปกติ" (select (== S 1) "ก่อนลอกคราบ (งดอาหาร)" (select (== S 2) "กำลังลอกคราบ" "ตัวนิ่ม ห้ามให้อาหาร")))))
''')

fn('Pct', [('Label', 'string'), ('V', 'float'), ('Unit', 'string')], [('S', 'string')])
dsl('Pct', '''
(fn Pct (Label V Unit)
  (return (Utilities|String|Append (Utilities|String|Append Label (Utilities|String|ToString(Integer) (Math|Float|Round V))) (Utilities|String|Append Unit NL))))
''')

# HUD text + log lines for what the spider did (compared with last frame)
fn('UpdateHUD', [('DT', 'float')])
dsl('UpdateHUD', '''
(fn UpdateHUD (DT)
  (bind st (Class|BPTarantula|GetStage :self Spider))
  (bind meals (Class|BPTarantula|GetMeals :self Spider))
  (if (> meals LastMeals) (Log :Msg "แมงมุมจับเหยื่อกินแล้ว"))
  (if (!= st LastStage) (Log :Msg (Utilities|String|Append "ระยะ: " (StageName :S st))))
  (Variables|Default|SetLastMeals meals)
  (Variables|Default|SetLastStage st)
  (bind h (Math|Float|Truncate Hours))
  (bind m (Math|Float|Truncate (* (- Hours h) 60.0)))
  (bind clock (Utilities|String|Append (Utilities|String|Append (select (< h 10) "0" "") (Utilities|String|ToString(Integer) h))
                 (Utilities|String|Append (select (< m 10) ":0" ":") (Utilities|String|ToString(Integer) m))))
  (bind a (Utilities|String|Append (Pct :Label "ความหิว  " :V (Class|BPTarantula|GetHunger :self Spider) :Unit "%")
                                 (Pct :Label "ความชื้น  " :V Hum :Unit "%")))
  (bind b (Utilities|String|Append (Pct :Label "อุณหภูมิ  " :V Temp :Unit " °C")
                                 (Pct :Label "การเติบโต  " :V (Class|BPTarantula|GetGrowth :self Spider) :Unit "%")))
  (bind c (Utilities|String|Append (Utilities|String|Append "ระยะ  " (StageName :S st))
             (Utilities|String|Append (Utilities|String|Append NL "ขนาดขา  ") (Utilities|String|Append (Utilities|String|ToString(Float) (/ (Math|Float|Round (/ (Class|BPTarantula|GetSpan :self Spider) 10.0)) 10.0)) (Utilities|String|Append " ซม." NL)))))
  (bind d (Utilities|String|Append (Utilities|String|Append "ลอกคราบ " (Utilities|String|ToString(Integer) (Class|BPTarantula|GetMolts :self Spider)))
             (Utilities|String|Append " ครั้ง · กินไป " (Utilities|String|Append (Utilities|String|ToString(Integer) meals) (Utilities|String|Append " ตัว" NL)))))
  (bind e (Utilities|String|Append (Utilities|String|Append "วันที่ " (Utilities|String|ToString(Integer) Day))
             (Utilities|String|Append (Utilities|String|Append "  เวลา " clock) (Utilities|String|Append "  ×" (Utilities|String|ToString(Integer) (Math|Float|Round TimeMul))))))
  (Widget|SetText(Text) :self (Class|WBPHUD|GetTxtStats :self HUD) :InText (Utilities|Text|ToText(String) (Utilities|String|Append (Utilities|String|Append a b) (Utilities|String|Append (Utilities|String|Append c d) e))))
  (Widget|SetText(Text) :self (Class|WBPHUD|GetTxtLog :self HUD) :InText (Utilities|Text|ToText(String) (Utilities|String|Append (Utilities|String|Append "บันทึก" NL) LogText)))
  (Variables|Default|SetNoticeT (- NoticeT DT))
  (Widget|SetText(Text) :self (Class|WBPHUD|GetTxtNotice :self HUD) :InText (Utilities|Text|ToText(String) (select (> NoticeT 0.0) Notice ""))))
''')

fn('SaveNow')
dsl('SaveNow', '''
(fn SaveNow ()
  (bind o (SaveGame|CreateSaveGameObject :SaveGameClass "/Game/Game/SG_Tarantula.SG_Tarantula_C"))
  (bind s (Utilities|Casting|CastToSG_Tarantula :Object o)
    (:then
      (Class|SGTarantula|SetSpan :self s :Span (Class|BPTarantula|GetSpan :self Spider))
      (Class|SGTarantula|SetHunger :self s :Hunger (Class|BPTarantula|GetHunger :self Spider))
      (Class|SGTarantula|SetGrowth :self s :Growth (Class|BPTarantula|GetGrowth :self Spider))
      (Class|SGTarantula|SetStage :self s :Stage (Class|BPTarantula|GetStage :self Spider))
      (Class|SGTarantula|SetStageT :self s :StageT (Class|BPTarantula|GetStageT :self Spider))
      (Class|SGTarantula|SetMolts :self s :Molts (Class|BPTarantula|GetMolts :self Spider))
      (Class|SGTarantula|SetMeals :self s :Meals (Class|BPTarantula|GetMeals :self Spider))
      (Class|SGTarantula|SetHum :self s :Hum Hum)
      (Class|SGTarantula|SetHours :self s :Hours Hours)
      (Class|SGTarantula|SetDay :self s :Day Day)
      (SaveGame|SaveGametoSlot :SaveGameObject s :SlotName "tarantula3d" :UserIndex 0))
    (:CastFailed)))
''')

fn('LoadNow')
dsl('LoadNow', '''
(fn LoadNow ()
  (if (SaveGame|DoesSaveGameExist :SlotName "tarantula3d" :UserIndex 0)
    (bind o (SaveGame|LoadGamefromSlot :SlotName "tarantula3d" :UserIndex 0))
    (bind s (Utilities|Casting|CastToSG_Tarantula :Object o)
      (:then
        (Class|BPTarantula|SetSpan :self Spider :Span (Class|SGTarantula|GetSpan :self s))
        (Class|BPTarantula|SetHunger :self Spider :Hunger (Class|SGTarantula|GetHunger :self s))
        (Class|BPTarantula|SetGrowth :self Spider :Growth (Class|SGTarantula|GetGrowth :self s))
        (Class|BPTarantula|SetStage :self Spider :Stage (Class|SGTarantula|GetStage :self s))
        (Class|BPTarantula|SetStageT :self Spider :StageT (Class|SGTarantula|GetStageT :self s))
        (Class|BPTarantula|SetMolts :self Spider :Molts (Class|SGTarantula|GetMolts :self s))
        (Class|BPTarantula|SetMeals :self Spider :Meals (Class|SGTarantula|GetMeals :self s))
        (Variables|Default|SetHum (Class|SGTarantula|GetHum :self s))
        (Variables|Default|SetHours (Class|SGTarantula|GetHours :self s))
        (Variables|Default|SetDay (Class|SGTarantula|GetDay :self s))
        (Variables|Default|SetLastMeals (Class|SGTarantula|GetMeals :self s))
        (Variables|Default|SetLastStage (Class|SGTarantula|GetStage :self s))
        (Class|BPTarantula|Build :self Spider)
        (Log :Msg "โหลดเซฟเดิมแล้ว"))
      (:CastFailed))))
''')

dsl('EventGraph', '''
(event EventBeginPlay
  (Variables|Default|SetSpider (Actor|GetActorOfClass :ActorClass "/Game/Spider/BP_Tarantula.BP_Tarantula_C"))
  (Variables|Default|SetSun (Actor|GetActorOfClass :ActorClass "/Script/Engine.DirectionalLight"))
  (Variables|Default|SetFog (Actor|GetActorOfClass :ActorClass "/Script/Engine.ExponentialHeightFog"))
  (bind pc (Game|GetPlayerController :PlayerIndex 0))
  (Class|PlayerController|SetShowMouseCursor :self pc :bShowMouseCursor true)
  (Input|SetInputModeGameAndUI :PlayerController pc :bHideCursorDuringCapture false)
  (Variables|Default|SetHUD (UserInterface|CreateWidget :Class "/Game/Game/WBP_HUD.WBP_HUD_C" :OwningPlayer pc))
  (UserInterface|Viewport|AddtoViewport :self HUD)
  (Variables|Default|SetYaw -90.0)
  (Variables|Default|SetPitch -26.0)
  (Variables|Default|SetDist 4200.0)
  (Variables|Default|SetDistNow 4200.0)
  (Variables|Default|SetFocus (Math|Vector|MakeVector -2300.0 1300.0 250.0))
  (Variables|Default|SetTimeMul 1.0)
  (Variables|Default|SetHum 75.0)
  (Variables|Default|SetHours 18.0)
  (Variables|Default|SetDay 1)
  (Log :Msg "ยินดีต้อนรับสู่ตู้บึ้งไทย — กด H ดูวิธีเล่น")
  (LoadNow))
(event EventTick (DeltaSeconds)
  (bind dt (Math|Float|Min(Float) DeltaSeconds 0.1))
  (Utilities|IsValid Spider
    (:"Is Valid"
      (Controls :DT dt)
      (Clock :DT dt)
      (Camera :DT dt)
      (UpdateHUD :DT dt)
      (Variables|Default|SetSaveT (+ SaveT dt))
      (if (> SaveT 15.0)
        (Variables|Default|SetSaveT 0.0)
        (SaveNow)))))
''')
compile()
# the DSL has no newline escape: the NL member's default value holds one
print('NL', call('editor_toolset.toolsets.object.ObjectTools', 'set_properties', {'instance': {'refPath': '/Game/Game/BP_Keeper.Default__BP_Keeper_C'}, 'values': json.dumps({'NL': '\n'})}))
