# BP_Keeper: the player (game.js camera + buttons + tank climate + save). Orbit camera on a spring arm around Focus
# (RMB drag = turn, wheel = zoom, WASD = pan, F = follow the spider), keys/buttons: 1 cricket, 2 dubia, M mist, T time speed,
# H help. Clock: 1 real s = 0.5 h x TimeMul (same as BP_Tarantula Needs); sun follows the hour; humidity falls, mist raises it.
target('/Game/Game/BP_Keeper', '/Script/Engine.Pawn')
comp('Arm', '/Script/Engine.SpringArmComponent', {'bDoCollisionTest': False, 'TargetArmLength': 3800.0})
comp('Cam', '/Script/Engine.CameraComponent', {'FieldOfView': 55.0}, parent='Arm')
for n, t in [('Yaw', 'float'), ('Pitch', 'float'), ('Dist', 'float'), ('DistNow', 'float'), ('Focus', 'Vector'), ('Follow', 'bool'),
             ('Hours', 'float'), ('Day', 'int'), ('Hum', 'float'), ('Temp', 'float'), ('TimeMul', 'float'), ('SaveT', 'float'),
             ('MistT', 'float'), ('Notice', 'string'), ('NoticeT', 'float'), ('LogText', 'string'),
             ('LastMeals', 'int'), ('LastStage', 'int'), ('Found', 'bool'), ('SpawnP', 'Vector'),
             ('NL', 'string'), ('AutoFed', 'bool'), ('AutoMist', 'bool'), ('Fps', 'float'), ('RoundOn', 'bool'), ('RoundT', 'float'), ('RoundDay', 'int'), ('Deaths', 'int'), ('Rescue', 'bool'), ('R0', 'float'), ('R1', 'float'), ('Rounds', 'int'), ('BestD', 'float'), ('BestP', 'Vector'), ('P7', 'bool'), ('P1', 'bool'), ('P2', 'bool'), ('P3', 'bool'), ('P4', 'bool'), ('P5', 'bool'), ('P6', 'bool')]:
    var(n, t)
objvar('Spider', '/Game/Spider/BP_Tarantula.BP_Tarantula_C')
objvar('HUD', '/Game/Game/WBP_HUD.WBP_HUD_C')
objvar('SG', '/Game/Game/SG_Tarantula.SG_Tarantula_C')
objvar('Sun', '/Script/Engine.DirectionalLight')
objvar('H0', '/Game/Game/BP_Human.BP_Human_C')
objvar('H1', '/Game/Game/BP_Human.BP_Human_C')
objvar('Heli1', '/Game/Game/BP_Heli.BP_Heli_C')
objvar('Heli2', '/Game/Game/BP_Heli.BP_Heli_C')
var('Spawns', 'Vector', True)
objvar('Fog', '/Script/Engine.ExponentialHeightFog')

# the DSL's (Utilities|IsValid x) is the exec macro: as a value it cuts the flow, so wrap it
fn('Valid', [('A', '/Script/Engine.Actor')], [('Ok', 'bool')])
dsl('Valid', '''
(fn Valid (A)
  (Utilities|IsValid A
    (:"Is Valid" (return true))
    (:"Is Not Valid" (return false))))
''')

# "[HH:MM] text" on top of the log (kept short)
fn('Log', [('Msg', 'string')])
dsl('Log', '''
(fn Log (Msg)
  (bind h (Math|Float|Truncate Hours))
  (bind m (Math|Float|Truncate (* (- Hours h) 60.0)))
  (bind hh (Utilities|String|Append (select (< h 10) "0" "") (Utilities|String|ToString(Integer) h)))
  (bind mm (Utilities|String|Append (select (< m 10) "0" "") (Utilities|String|ToString(Integer) m)))
  (bind line (Utilities|String|Append (Utilities|String|Append (Utilities|String|Append "[" hh) (Utilities|String|Append ":" mm)) (Utilities|String|Append "] " Msg)))
  (Variables|Default|SetLogText (Utilities|String|Left (Utilities|String|Append (Utilities|String|Append line NL) LogText) 700)))
''')

fn('Say', [('Msg', 'string')])
dsl('Say', '''
(fn Say (Msg)
  (Variables|Default|SetNotice Msg)
  (Variables|Default|SetNoticeT 3.5))
''')

# release prey: max 4, never while molting / soft (live prey is dangerous then), away from the spider, not in the pond
fn('SpawnPrey', [('Kind', 'int')])
dsl('SpawnPrey', '''
(fn SpawnPrey (Kind)
  (bind all (Actor|GetAllActorsOfClass :ActorClass "/Game/Game/BP_Prey.BP_Prey_C"))
  (bind st (Class|BPTarantula|GetStage :self Spider))
  (if (>= (Utilities|Array|Length all) 4)
    (Say :Msg "ในตู้มีเหยื่อครบ 4 ตัวแล้ว")
    (elif (>= st 2)
      (Say :Msg "ห้ามให้อาหารตอนลอกคราบ/ตัวนิ่ม — เหยื่อเป็นอันตรายต่อแมงมุม")
      (else
        (bind span (Class|BPTarantula|GetSpan :self Spider))
        (bind sp (Transformation|GetActorLocation :self Spider))
        (Variables|Default|SetFound false)
        (for i (range 30)
          (bind p (Math|Vector|MakeVector (Math|Random|RandomFloatinRange -5200.0 1300.0) (Math|Random|RandomFloatinRange -700.0 3500.0) 600.0))
          (bind ok (and (> (Math|Vector|Distance2D(Vector) p sp) (+ (* span 2.5) 600.0)) (> (Math|Vector|Distance2D(Vector) p (Math|Vector|MakeVector 300.0 2550.0 0.0)) 850.0)))
          (if (and ok (not Found))
            (Variables|Default|SetFound true)
            (Variables|Default|SetSpawnP p)))
        (bind a (Game|SpawnActorfromClass :Class "/Game/Game/BP_Prey.BP_Prey_C"
                   :SpawnTransform (Math|Transform|MakeTransform :Location SpawnP) :CollisionHandlingOverride "AlwaysSpawn"))
        (Class|BPPrey|SetKind :self a :Kind Kind)
        (Class|BPPrey|SetK :self a :K (/ span 1200.0))
        (Class|BPPrey|Setup :self a)
        (if (== st 1) (Say :Msg "ช่วงก่อนลอกคราบ แมงมุมจะไม่กินอาหาร"))
        (Log :Msg (select (== Kind 0) "ปล่อยจิ้งหรีดลงตู้" "ปล่อยแมลงสาบดูเบียลงตู้"))))))
''')

fn('Mist')
dsl('Mist', '''
(fn Mist ()
  (Variables|Default|SetHum (Math|Float|Min(Float) 100.0 (+ Hum 30.0)))
  (Variables|Default|SetMistT 8.0)
  (Log :Msg (Utilities|String|Append "พ่นน้ำ ความชื้นเป็น " (Utilities|String|Append (Utilities|String|ToString(Integer) (Math|Float|Round Hum)) "%"))))
''')

fn('CycleSpeed')
dsl('CycleSpeed', '''
(fn CycleSpeed ()
  (Variables|Default|SetTimeMul (select (< TimeMul 5.0) 10.0 (select (< TimeMul 30.0) 60.0 1.0)))
  (Say :Msg (Utilities|String|Append "ความเร็วเวลา x" (Utilities|String|ToString(Integer) (Math|Float|Round TimeMul)))))
''')

fn('ToggleHelp')
dsl('ToggleHelp', '''
(fn ToggleHelp ()
  (bind box (Class|WBPHUD|GetHelpBox :self HUD))
  (bind vis (Widget|IsVisible :self box))
  (if vis
    (Widget|SetVisibility :self box :InVisibility "Collapsed")
    (else (Widget|SetVisibility :self box :InVisibility "Visible"))))
''')

fn('ToggleFollow')
dsl('ToggleFollow', '''
(fn ToggleFollow ()
  (Variables|Default|SetFollow (not Follow))
  (Say :Msg (select Follow "กล้องติดตามแมงมุม" "กล้องอิสระ")))
''')

# keyboard + mouse (the HUD buttons call the same functions from WBP_HUD's OnClicked events)
fn('Controls', [('DT', 'float')])
dsl('Controls', '''
(fn Controls (DT)
  (bind pc (Game|GetPlayerController :PlayerIndex 0))
  (bind (mx my) (Game|Player|GetInputMouseDelta :self pc))
  (if (Game|Player|IsInputKeyDown :self pc :Key "RightMouseButton")
    (Variables|Default|SetYaw (+ Yaw (* mx 0.3)))
    (Variables|Default|SetPitch (Math|Float|Clamp(Float) (+ Pitch (* my 0.3)) -85.0 -4.0)))
  (if (Game|Player|WasInputKeyJustPressed :self pc :Key "MouseScrollUp") (Variables|Default|SetDist (Math|Float|Max(Float) 350.0 (* Dist 0.86))))
  (if (Game|Player|WasInputKeyJustPressed :self pc :Key "MouseScrollDown") (Variables|Default|SetDist (Math|Float|Min(Float) 30000.0 (* Dist 1.16))))
  (bind fwd (Math|Vector|MakeVector (Math|Trig|Cos(Degrees) Yaw) (Math|Trig|Sin(Degrees) Yaw) 0.0))
  (bind right (Math|Vector|MakeVector (- 0.0 (Math|Trig|Sin(Degrees) Yaw)) (Math|Trig|Cos(Degrees) Yaw) 0.0))
  (bind f (- (select (Game|Player|IsInputKeyDown :self pc :Key "W") 1.0 0.0) (select (Game|Player|IsInputKeyDown :self pc :Key "S") 1.0 0.0)))
  (bind r (- (select (Game|Player|IsInputKeyDown :self pc :Key "D") 1.0 0.0) (select (Game|Player|IsInputKeyDown :self pc :Key "A") 1.0 0.0)))
  (if (or (!= f 0.0) (!= r 0.0))
    (Variables|Default|SetFollow false)
    (bind mv (* (+ (* fwd f) (* right r)) (* (* Dist 0.7) DT)))
    (bind nf (+ Focus mv))
    (Variables|Default|SetFocus (Math|Vector|MakeVector (Math|Float|Clamp(Float) (.x nf) -6500.0 6500.0) (Math|Float|Clamp(Float) (.y nf) -4500.0 4500.0) (.z nf))))
  (if (Game|Player|WasInputKeyJustPressed :self pc :Key "P") (StartRound))
  (if (Game|Player|WasInputKeyJustPressed :self pc :Key "One") (SpawnPrey :Kind 0))
  (if (Game|Player|WasInputKeyJustPressed :self pc :Key "Two") (SpawnPrey :Kind 1))
  (if (Game|Player|WasInputKeyJustPressed :self pc :Key "M") (Mist))
  (if (Game|Player|WasInputKeyJustPressed :self pc :Key "F") (ToggleFollow))
  (if (Game|Player|WasInputKeyJustPressed :self pc :Key "T") (CycleSpeed))
  (if (Game|Player|WasInputKeyJustPressed :self pc :Key "H") (ToggleHelp)))
''')

fn('Camera', [('DT', 'float')])
dsl('Camera', '''
(fn Camera (DT)
  (if Follow
    (bind sp (Transformation|GetActorLocation :self Spider))
    (Variables|Default|SetFocus (Math|Interpolation|VInterpTo Focus sp DT 3.0)))
  (Variables|Default|SetDistNow (Math|Interpolation|FInterpTo DistNow Dist DT 6.0))
  (Transformation|SetActorLocation :self self :NewLocation Focus)
  (Transformation|SetWorldRotation :self Arm :NewRotation (Math|Rotator|MakeRotator 0.0 Pitch Yaw))
  (Class|SpringArmComponent|SetTargetArmLength :self Arm :TargetArmLength DistNow))
''')

# clock, sun, humidity, temperature, spider time scale, mist fog
fn('Clock', [('DT', 'float')])
dsl('Clock', '''
(fn Clock (DT)
  (bind hrs (* (* DT 0.5) TimeMul))
  (Class|BPTarantula|SetTimeScale :self Spider :TimeScale TimeMul)
  (bind nh (+ Hours hrs))
  (if (>= nh 24.0)
    (Variables|Default|SetDay (+ Day 1))
    (Log :Msg (Utilities|String|Append "เริ่มวันที่ " (Utilities|String|ToString(Integer) Day))))
  (Variables|Default|SetHours (select (>= nh 24.0) (- nh 24.0) nh))
  (Variables|Default|SetHum (Math|Float|Max(Float) 25.0 (- Hum (* hrs 0.6))))
  (bind s (Math|Trig|Sin(Radians) (* (/ (- Hours 6.0) 12.0) 3.1416)))
  (Variables|Default|SetTemp (+ 25.5 (* 3.0 s)))
  (Transformation|SetActorRotation :self Sun :NewRotation (Math|Rotator|MakeRotator 0.0 (- 0.0 (Math|Float|Max(Float) 10.0 (* 62.0 s))) (+ 30.0 (* Hours 4.0))) :bTeleportPhysics false)
  (bind lc (Actor|GetComponentbyClass :self Sun :ComponentClass "/Script/Engine.LightComponent"))
  (Rendering|Components|Light|SetIntensity :self lc :NewIntensity (Math|Float|Lerp 1.6 6.0 (Math|Float|Clamp(Float) (* s 2.5) 0.0 1.0)))
  (Variables|Default|SetMistT (Math|Float|Max(Float) 0.0 (- MistT DT)))
  (bind fc (Actor|GetComponentbyClass :self Fog :ComponentClass "/Script/Engine.ExponentialHeightFogComponent"))
  (Rendering|Components|ExponentialHeightFog|SetFogDensity :self fc :Value (+ 0.02 (* MistT 0.012))))
''')


# survival round (js/survive.js ROUND): both people walk in far from the spider; eaten -> back after 10 s; day 30 -> helicopters
fn('SpawnHuman', [('Who', 'int'), ('Other', 'Vector')], [('H', '/Game/Game/BP_Human.BP_Human_C')])
dsl('SpawnHuman', '''
(fn SpawnHuman (Who Other)
  (bind sp (Transformation|GetActorLocation :self Spider))
  (Variables|Default|SetBestD -1.0)
  (for p Spawns
    (bind score (+ (Math|Vector|Distance2D(Vector) p sp) (* (Math|Random|RandomFloat) 2500.0)))
    (if (and (> score BestD) (> (Math|Vector|Distance2D(Vector) p Other) 1500.0))
      (Variables|Default|SetBestD score)
      (Variables|Default|SetBestP p)))
  (bind h (Game|SpawnActorfromClass :Class "/Game/Game/BP_Human.BP_Human_C"
            :SpawnTransform (Math|Transform|MakeTransform :Location (+ BestP (Math|Vector|MakeVector 0.0 0.0 30.0))) :CollisionHandlingOverride "AlwaysSpawn"))
  (Class|BPHuman|SetWho :self h :Who Who)
  (Class|BPHuman|Setup :self h)
  (Log :Msg (Utilities|String|Append (select (== Who 0) "ชัยภัทร" "ตุ้ย") "หลงเข้ามาในเมืองร้าง ต้องหาของกิน หาน้ำ และหลบแมงมุมยักษ์ให้ได้ 30 วัน"))
  (return h))
''')

fn('StartRound')
dsl('StartRound', '''
(fn StartRound ()
  (bind span (Class|BPTarantula|GetSpan :self Spider))
  (if (< span 1200.0)
    (Say :Msg (Utilities|String|Append "แมงมุมต้องขาใหญ่ถึง 12 ซม. ก่อน คนถึงจะกลัว (ตอนนี้ " (Utilities|String|Append (Utilities|String|ToString(Float) (/ (Math|Float|Round (/ span 10.0)) 10.0)) " ซม.)")))
    (elif RoundOn
      (Say :Msg "ภารกิจเอาชีวิตรอดกำลังเล่นอยู่")
      (else
        (Variables|Default|SetRoundOn true)
        (Variables|Default|SetRoundT 0.0)
        (Variables|Default|SetRoundDay 0)
        (Variables|Default|SetDeaths 0)
        (Variables|Default|SetRescue false)
        (Variables|Default|SetR0 -1.0)
        (Variables|Default|SetR1 -1.0)
        (Log :Msg "เริ่มภารกิจเอาชีวิตรอด: ชัยภัทรกับตุ้ยต้องรอดในเมืองร้าง 30 วัน (1 วัน = 12 วินาที) แล้วเฮลิคอปเตอร์จะมารับ")
        (Variables|Default|SetH0 (SpawnHuman :Who 0 :Other (Math|Vector|MakeVector 99999.0 0.0 0.0)))
        (Variables|Default|SetH1 (SpawnHuman :Who 1 :Other (Transformation|GetActorLocation :self H0)))
        (Say :Msg "ปล่อยชัยภัทรกับตุ้ยเข้าเมืองแล้ว")))))
''')

fn('EndRound')
dsl('EndRound', '''
(fn EndRound ()
  (bind v0 (Valid :A H0))
  (bind v1 (Valid :A H1))
  (bind s0 (and v0 (Class|BPHuman|GetBoarded :self H0)))
  (bind s1 (and v1 (Class|BPHuman|GetBoarded :self H1)))
  (bind stars (select (== Deaths 0) 3 (select (== Deaths 1) 2 1)))
  (bind star (select (== stars 3) "3 ดาว" (select (== stars 2) "2 ดาว" "1 ดาว")))
  (Variables|Default|SetRounds (+ Rounds 1))
  (Log :Msg (Utilities|String|Append (Utilities|String|Append "ภารกิจสำเร็จ! ขึ้นเฮลิคอปเตอร์ได้ " (Utilities|String|ToString(Integer) (+ (select s0 1 0) (select s1 1 0))))
             (Utilities|String|Append (Utilities|String|Append " คน · ถูกกินระหว่างรอบ " (Utilities|String|ToString(Integer) Deaths)) (Utilities|String|Append " ครั้ง · ได้ " star))))
  (Say :Msg (Utilities|String|Append "รอดครบ 30 วัน ได้ " star))
  (Variables|Default|SetRoundOn false)
  (if v0 (Actor|DestroyActor :self H0))
  (if v1 (Actor|DestroyActor :self H1))
  (Class|BPHeli|SetMode :self Heli1 :Mode 0)
  (Class|BPHeli|SetDone :self Heli1 :Done false)
  (Rendering|SetActorHiddenInGame :self Heli1 :bNewHidden false)
  (Class|BPHeli|SetMode :self Heli2 :Mode 0)
  (Class|BPHeli|SetDone :self Heli2 :Done false)
  (Rendering|SetActorHiddenInGame :self Heli2 :bNewHidden false))
''')

fn('RoundTick', [('DT', 'float')])
dsl('RoundTick', '''
(fn RoundTick (DT)
  (Variables|Default|SetRoundT (+ RoundT (* DT TimeMul)))
  (bind day (Math|Float|Truncate (/ RoundT 12.0)))
  (if (> day RoundDay)
    (Variables|Default|SetRoundDay day)
    (if (and (== (Math|Integer|%(Integer) day 5) 0) (< day 30))
      (Log :Msg (Utilities|String|Append "เอาชีวิตรอดวันที่ " (Utilities|String|ToString(Integer) day)))))
  (bind v0 (Valid :A H0))
  (bind v1 (Valid :A H1))
  (if (not Rescue)
    (if (and (not v0) (< R0 0.0))
      (Variables|Default|SetDeaths (+ Deaths 1)) (Variables|Default|SetR0 10.0)
      (Log :Msg "ชัยภัทรถูกแมงมุมกิน! ตุ้ย: ไม่นะ... ชัยภัทร!!"))
    (if (and (not v1) (< R1 0.0))
      (Variables|Default|SetDeaths (+ Deaths 1)) (Variables|Default|SetR1 10.0)
      (Log :Msg "ตุ้ยถูกแมงมุมกิน! ชัยภัทร: ตุ้ย!! ไม่ต้องห่วง ฉันจะรอดให้ได้"))
    (if (>= R0 0.0)
      (Variables|Default|SetR0 (- R0 DT))
      (if (< R0 0.0) (Variables|Default|SetH0 (SpawnHuman :Who 0 :Other (Math|Vector|MakeVector 99999.0 0.0 0.0)))))
    (if (>= R1 0.0)
      (Variables|Default|SetR1 (- R1 DT))
      (if (< R1 0.0) (Variables|Default|SetH1 (SpawnHuman :Who 1 :Other (Math|Vector|MakeVector 99999.0 0.0 0.0))))))
  (if (and (>= day 30) (not Rescue))
    (Variables|Default|SetRescue true)
    (Log :Msg "ครบ 30 วันแล้ว! เฮลิคอปเตอร์กู้ภัยบินลงมารับ")
    (Say :Msg "ครบ 30 วัน! เฮลิคอปเตอร์มาแล้ว")
    (if v0 (Class|BPHeli|Rescue :self Heli1 :Who H0))
    (if v1 (Class|BPHeli|Rescue :self Heli2 :Who H1)))
  (if Rescue
    (bind d0 (or (not v0) (Class|BPHuman|GetBoarded :self H0)))
    (bind d1 (or (not v1) (Class|BPHuman|GetBoarded :self H1)))
    (if (and (and d0 d1) (or (Class|BPHeli|GetDone :self Heli1) (Class|BPHeli|GetDone :self Heli2)))
      (EndRound))))
''')

# auto-care once per crisis (game.js S.autoFed hunger >= 85, S.autoMist humidity < 55)
fn('AutoCare')
dsl('AutoCare', '''
(fn AutoCare ()
  (bind hu (Class|BPTarantula|GetHunger :self Spider))
  (bind st (Class|BPTarantula|GetStage :self Spider))
  (bind n (Utilities|Array|Length (Actor|GetAllActorsOfClass :ActorClass "/Game/Game/BP_Prey.BP_Prey_C")))
  (if (and (>= hu 85.0) (and (not AutoFed) (and (== st 0) (== n 0))))
    (Variables|Default|SetAutoFed true)
    (Log :Msg "ดูแลอัตโนมัติ: แมงมุมหิวมาก ปล่อยจิ้งหรีดให้ 1 ตัว")
    (SpawnPrey :Kind 0))
  (if (< hu 60.0) (Variables|Default|SetAutoFed false))
  (if (and (< Hum 55.0) (not AutoMist))
    (Variables|Default|SetAutoMist true)
    (Log :Msg "ดูแลอัตโนมัติ: ตู้แห้งเกินไป พ่นน้ำให้")
    (Mist))
  (if (> Hum 70.0) (Variables|Default|SetAutoMist false)))
''')

fn('StageName', [('S', 'int')], [('N', 'string')])
dsl('StageName', '''
(fn StageName (S)
  (return (select (== S 0) "ปกติ" (select (== S 1) "ก่อนลอกคราบ (งดอาหาร)" (select (== S 2) "กำลังลอกคราบ" "ตัวนิ่ม ห้ามให้อาหาร")))))
''')

fn('Pct', [('Label', 'string'), ('V', 'float'), ('Unit', 'string')], [('S', 'string')])
dsl('Pct', '''
(fn Pct (Label V Unit)
  (return (Utilities|String|Append (Utilities|String|Append Label (Utilities|String|ToString(Integer) (Math|Float|Round V))) (Utilities|String|Append Unit NL))))
''')

# HUD text + log lines for what the spider did (compared with last frame)
fn('UpdateHUD', [('DT', 'float')])
dsl('UpdateHUD', '''
(fn UpdateHUD (DT)
  (bind st (Class|BPTarantula|GetStage :self Spider))
  (bind meals (Class|BPTarantula|GetMeals :self Spider))
  (if (> meals LastMeals) (Log :Msg "แมงมุมจับเหยื่อกินแล้ว"))
  (if (!= st LastStage) (Log :Msg (Utilities|String|Append "ระยะ: " (StageName :S st))))
  (Variables|Default|SetLastMeals meals)
  (Variables|Default|SetLastStage st)
  (bind h (Math|Float|Truncate Hours))
  (bind m (Math|Float|Truncate (* (- Hours h) 60.0)))
  (bind clock (Utilities|String|Append (Utilities|String|Append (select (< h 10) "0" "") (Utilities|String|ToString(Integer) h))
                 (Utilities|String|Append (select (< m 10) ":0" ":") (Utilities|String|ToString(Integer) m))))
  (bind a (Utilities|String|Append (Pct :Label "ความหิว  " :V (Class|BPTarantula|GetHunger :self Spider) :Unit "%")
                                 (Pct :Label "ความชื้น  " :V Hum :Unit "%")))
  (bind b (Utilities|String|Append (Pct :Label "อุณหภูมิ  " :V Temp :Unit " °C")
                                 (Pct :Label "การเติบโต  " :V (Class|BPTarantula|GetGrowth :self Spider) :Unit "%")))
  (bind c (Utilities|String|Append (Utilities|String|Append "ระยะ  " (StageName :S st))
             (Utilities|String|Append (Utilities|String|Append NL "ขนาดขา  ") (Utilities|String|Append (Utilities|String|ToString(Float) (/ (Math|Float|Round (/ (Class|BPTarantula|GetSpan :self Spider) 10.0)) 10.0)) (Utilities|String|Append " ซม." NL)))))
  (bind d (Utilities|String|Append (Utilities|String|Append "ลอกคราบ " (Utilities|String|ToString(Integer) (Class|BPTarantula|GetMolts :self Spider)))
             (Utilities|String|Append " ครั้ง · กินไป " (Utilities|String|Append (Utilities|String|ToString(Integer) meals) (Utilities|String|Append " ตัว" NL)))))
  (bind e (Utilities|String|Append (Utilities|String|Append "วันที่ " (Utilities|String|ToString(Integer) Day))
             (Utilities|String|Append (Utilities|String|Append "  เวลา " clock) (Utilities|String|Append (Utilities|String|Append "  ×" (Utilities|String|ToString(Integer) (Math|Float|Round TimeMul))) (Utilities|String|Append "  FPS " (Utilities|String|ToString(Integer) (Math|Float|Round Fps)))))))
  (bind r (select RoundOn (Utilities|String|Append (Utilities|String|Append (Utilities|String|Append NL "เอาชีวิตรอด วันที่ ") (Utilities|String|ToString(Integer) RoundDay))
             (Utilities|String|Append "/30 · ถูกกิน " (Utilities|String|Append (Utilities|String|ToString(Integer) Deaths) " ครั้ง"))) ""))
  (Widget|SetText(Text) :self (Class|WBPHUD|GetTxtStats :self HUD) :InText (Utilities|Text|ToText(String) (Utilities|String|Append (Utilities|String|Append (Utilities|String|Append a b) (Utilities|String|Append (Utilities|String|Append c d) e)) r)))
  (Widget|SetText(Text) :self (Class|WBPHUD|GetTxtLog :self HUD) :InText (Utilities|Text|ToText(String) (Utilities|String|Append (Utilities|String|Append "บันทึก" NL) LogText)))
  (Variables|Default|SetNoticeT (- NoticeT DT))
  (Widget|SetText(Text) :self (Class|WBPHUD|GetTxtNotice :self HUD) :InText (Utilities|Text|ToText(String) (select (> NoticeT 0.0) Notice ""))))
''')

fn('SaveNow')
dsl('SaveNow', '''
(fn SaveNow ()
  (bind o (SaveGame|CreateSaveGameObject :SaveGameClass "/Game/Game/SG_Tarantula.SG_Tarantula_C"))
  (bind s (Utilities|Casting|CastToSG_Tarantula :Object o)
    (:then
      (Class|SGTarantula|SetSpan :self s :Span (Class|BPTarantula|GetSpan :self Spider))
      (Class|SGTarantula|SetHunger :self s :Hunger (Class|BPTarantula|GetHunger :self Spider))
      (Class|SGTarantula|SetGrowth :self s :Growth (Class|BPTarantula|GetGrowth :self Spider))
      (Class|SGTarantula|SetStage :self s :Stage (Class|BPTarantula|GetStage :self Spider))
      (Class|SGTarantula|SetStageT :self s :StageT (Class|BPTarantula|GetStageT :self Spider))
      (Class|SGTarantula|SetMolts :self s :Molts (Class|BPTarantula|GetMolts :self Spider))
      (Class|SGTarantula|SetMeals :self s :Meals (Class|BPTarantula|GetMeals :self Spider))
      (Class|SGTarantula|SetHum :self s :Hum Hum)
      (Class|SGTarantula|SetHours :self s :Hours Hours)
      (Class|SGTarantula|SetDay :self s :Day Day)
      (SaveGame|SaveGametoSlot :SaveGameObject s :SlotName "tarantula3d" :UserIndex 0))
    (:CastFailed)))
''')

fn('LoadNow')
dsl('LoadNow', '''
(fn LoadNow ()
  (if (SaveGame|DoesSaveGameExist :SlotName "tarantula3d" :UserIndex 0)
    (bind o (SaveGame|LoadGamefromSlot :SlotName "tarantula3d" :UserIndex 0))
    (bind s (Utilities|Casting|CastToSG_Tarantula :Object o)
      (:then
        (Class|BPTarantula|SetSpan :self Spider :Span (Class|SGTarantula|GetSpan :self s))
        (Class|BPTarantula|SetHunger :self Spider :Hunger (Class|SGTarantula|GetHunger :self s))
        (Class|BPTarantula|SetGrowth :self Spider :Growth (Class|SGTarantula|GetGrowth :self s))
        (Class|BPTarantula|SetStage :self Spider :Stage (Class|SGTarantula|GetStage :self s))
        (Class|BPTarantula|SetStageT :self Spider :StageT (Class|SGTarantula|GetStageT :self s))
        (Class|BPTarantula|SetMolts :self Spider :Molts (Class|SGTarantula|GetMolts :self s))
        (Class|BPTarantula|SetMeals :self Spider :Meals (Class|SGTarantula|GetMeals :self s))
        (Variables|Default|SetHum (Class|SGTarantula|GetHum :self s))
        (Variables|Default|SetHours (Class|SGTarantula|GetHours :self s))
        (Variables|Default|SetDay (Class|SGTarantula|GetDay :self s))
        (Variables|Default|SetLastMeals (Class|SGTarantula|GetMeals :self s))
        (Variables|Default|SetLastStage (Class|SGTarantula|GetStage :self s))
        (Class|BPTarantula|Build :self Spider)
        (Log :Msg "โหลดเซฟเดิมแล้ว"))
      (:CastFailed))))
''')

dsl('EventGraph', '''
(event EventBeginPlay
  (Variables|Default|SetSpider (Actor|GetActorOfClass :ActorClass "/Game/Spider/BP_Tarantula.BP_Tarantula_C"))
  (Variables|Default|SetSun (Actor|GetActorOfClass :ActorClass "/Script/Engine.DirectionalLight"))
  (Variables|Default|SetFog (Actor|GetActorOfClass :ActorClass "/Script/Engine.ExponentialHeightFog"))
  (bind pc (Game|GetPlayerController :PlayerIndex 0))
  (Class|PlayerController|SetShowMouseCursor :self pc :bShowMouseCursor true)
  (Input|SetInputModeGameAndUI :PlayerController pc :bHideCursorDuringCapture false)
  (Variables|Default|SetHUD (UserInterface|CreateWidget :Class "/Game/Game/WBP_HUD.WBP_HUD_C" :OwningPlayer pc))
  (UserInterface|Viewport|AddtoViewport :self HUD)
  (Class|WBPHUD|SetKeeper :self HUD :Keeper self)
  (Variables|Default|SetYaw -90.0)
  (Variables|Default|SetPitch -32.0)
  (Variables|Default|SetDist 15000.0)
  (Variables|Default|SetDistNow 15000.0)
  (Variables|Default|SetFocus (Math|Vector|MakeVector -600.0 600.0 300.0))
  (Variables|Default|SetTimeMul 1.0)
  (Variables|Default|SetHum 75.0)
  (Variables|Default|SetHours 18.0)
  (Variables|Default|SetDay 1)
  (Variables|Default|SetHeli1 (Game|SpawnActorfromClass :Class "/Game/Game/BP_Heli.BP_Heli_C"
      :SpawnTransform (Math|Transform|MakeTransform :Location (Math|Vector|MakeVector 4600.0 0.0 4300.0)) :CollisionHandlingOverride "AlwaysSpawn"))
  (Variables|Default|SetHeli2 (Game|SpawnActorfromClass :Class "/Game/Game/BP_Heli.BP_Heli_C"
      :SpawnTransform (Math|Transform|MakeTransform :Location (Math|Vector|MakeVector -3800.0 0.0 3300.0)) :CollisionHandlingOverride "AlwaysSpawn"))
  (Class|BPHeli|SetColor :self Heli2 :Color 1)
  (Class|BPHeli|Setup :self Heli2)
  (bind amb (Audio|SpawnSound2D :Sound "/Game/Game/Sound/S_Room.S_Room" :VolumeMultiplier 0.3))
  (Log :Msg "ยินดีต้อนรับสู่ตู้บึ้งไทย — กด H ดูวิธีเล่น")
  (LoadNow))
(event EventTick (DeltaSeconds)
  (bind dt (Math|Float|Min(Float) DeltaSeconds 0.1))
  (Variables|Default|SetFps (Math|Float|Lerp Fps (/ 1.0 (Math|Float|Max(Float) DeltaSeconds 0.001)) 0.05))
  (Utilities|IsValid Spider
    (:"Is Valid"
      (Controls :DT dt)
      (Clock :DT dt)
      (Camera :DT dt)
      (UpdateHUD :DT dt)
      (if RoundOn (RoundTick :DT dt))
      (AutoCare)
      (Variables|Default|SetSaveT (+ SaveT dt))
      (if (> SaveT 15.0)
        (Variables|Default|SetSaveT 0.0)
        (SaveNow)))))
''')
edit('Dist', 'Follow', 'Pitch', 'Yaw')   # settable from MCP while playing (close-up screenshots)
compile()
SP = json.load(open('spots.json', encoding='utf-8'))
print('spawns', call('editor_toolset.toolsets.object.ObjectTools', 'set_properties', {'instance': {'refPath': '/Game/Game/BP_Keeper.Default__BP_Keeper_C'}, 'values': json.dumps({'Spawns': [{'x': p[0], 'y': p[1], 'z': p[2]} for p in SP['hides']]})}))
# the DSL has no newline escape: the NL member's default value holds one
print('NL', call('editor_toolset.toolsets.object.ObjectTools', 'set_properties', {'instance': {'refPath': '/Game/Game/BP_Keeper.Default__BP_Keeper_C'}, 'values': json.dumps({'NL': '\n'})}))
