# BP_Tarantula: variables + functions (port of js/spider.js legs/gait + game.js wander/needs). Units: cm (1 game unit = 100 cm)
target('/Game/Spider/BP_Tarantula')
for c in ('Body', 'Abdomen'): comp(c, '/Script/Engine.StaticMeshComponent')
for c in ('Legs', 'Knobs'): comp(c, '/Script/Engine.InstancedStaticMeshComponent')
for n, t in [('Span', 'float'), ('MaxSpan', 'float'), ('WanderRadius', 'float'), ('TimeScale', 'float'),
             ('Home', 'Vector'), ('Target', 'Vector'), ('Vel', 'Vector'), ('PauseT', 'float'), ('BurstT', 'float'),
             ('Speed', 'float'), ('Yaw', 'float'), ('YawRate', 'float'), ('Phase', 'float'), ('NSwing', 'int'),
             ('Hunger', 'float'), ('Growth', 'float'), ('Stage', 'int'), ('StageT', 'float'), ('Molts', 'int'), ('HasTarget', 'bool')]:
    var(n, t)
for n, t in [('HipL', 'Vector'), ('RestL', 'Vector'), ('Foot', 'Vector'), ('From', 'Vector'),
             ('LA', 'float'), ('LB', 'float'), ('LC', 'float'), ('LT', 'float'), ('Off', 'float'), ('LastP', 'float'),
             ('SwT', 'float'), ('SwDur', 'float'), ('Tuck', 'float'), ('Swing', 'bool')]:
    var(n, t, True)
objvar('NoWalk', '/Script/Engine.Actor', True)
objvar('Prey', '/Game/Game/BP_Prey.BP_Prey_C')
objvar('Victim', '/Game/Game/BP_Human.BP_Human_C')
for n, t in [('EatHuman', 'bool'), ('ChaseT', 'float'), ('IgnoreT', 'float'), ('BestH', 'float'), ('DTm', 'float'), ('Blocked', 'bool')]:
    var(n, t)
for n, t in [('Best', 'float'), ('Hunting', 'bool'), ('Eating', 'bool'), ('EatT', 'float'), ('Meals', 'int')]:
    var(n, t)   # actors tagged NoWalk (leaves, grass, moss shells): feet go through them

# ground height under P (complex trace, so it follows the real mesh surface)
fn('GroundZ', [('P', 'Vector')], [('Z', 'float')])
dsl('GroundZ', '''
(fn GroundZ (P)
  (bind (hit ok) (Collision|LineTraceByChannel
     :Start (+ P (Math|Vector|MakeVector 0.0 0.0 3000.0))
     :End (- P (Math|Vector|MakeVector 0.0 0.0 3000.0))
     :bTraceComplex true :ActorsToIgnore NoWalk))
  (if ok
    (bind (blk ovl tm dist loc imp) (Collision|BreakHitResult hit))
    (return (.z imp))
    (else (return (.z P)))))
''')

# volume by distance to the player camera (sounds have no attenuation assets)
fn('CamVol', [('P', 'Vector'), ('Far', 'float')], [('V', 'float')])
dsl('CamVol', '''
(fn CamVol (P Far)
  (bind cm (Game|GetPlayerCameraManager :PlayerIndex 0))
  (bind cl (Camera|GetCameraLocation :self cm))
  (return (Math|Float|Clamp(Float) (- 1.0 (/ (Math|Vector|Distance(Vector) cl P) Far)) 0.0 1.0)))
''')

fn('Valid', [('A', '/Script/Engine.Actor')], [('Ok', 'bool')])
dsl('Valid', '''
(fn Valid (A)
  (Utilities|IsValid A
    (:"Is Valid" (return true))
    (:"Is Not Valid" (return false))))
''')

fn('Seg', [('Idx', 'int'), ('A', 'Vector'), ('B', 'Vector'), ('R', 'float')])
dsl('Seg', '''
(fn Seg (Idx A B R)
  (bind d (- B A))
  (Components|InstancedStaticMesh|UpdateInstanceTransform :self Legs :InstanceIndex Idx
    :NewInstanceTransform (Math|Transform|MakeTransform
       :Location (* (+ A B) 0.5)
       :Rotation (Math|Rotator|MakeRotfromZ d)
       :Scale (Math|Vector|MakeVector (/ R 50.0) (/ R 50.0) (/ (Math|Vector|VectorLength d) 100.0)))
    :bWorldSpace true :bMarkRenderStateDirty true :bTeleport true))
''')

fn('Knob', [('Idx', 'int'), ('P', 'Vector'), ('R', 'float')])
dsl('Knob', '''
(fn Knob (Idx P R)
  (bind s (/ R 50.0))
  (Components|InstancedStaticMesh|UpdateInstanceTransform :self Knobs :InstanceIndex Idx
    :NewInstanceTransform (Math|Transform|MakeTransform :Location P :Scale (Math|Vector|MakeVector s s s))
    :bWorldSpace true :bMarkRenderStateDirty true :bTeleport true))
''')

# neutral foothold of leg I, TA seconds ahead (body keeps moving), dropped onto the ground
fn('RestAt', [('I', 'int'), ('TA', 'float')], [('W', 'Vector')])
dsl('RestAt', '''
(fn RestAt (I TA)
  (bind p (+ (Math|Transform|TransformLocation (Transformation|GetActorTransform) (Utilities|Array|Get(acopy) RestL I)) (* Vel TA)))
  (bind gz (GroundZ :P p))
  (return (Math|Vector|MakeVector (.x p) (.y p) (+ gz (* Span 0.005)))))
''')

fn('AddLeg', [('S', 'float'), ('Ang', 'float'), ('Fa', 'float'), ('Reach', 'float'), ('A', 'float'), ('B', 'float'), ('C', 'float'), ('T', 'float'), ('O', 'float')])
dsl('AddLeg', '''
(fn AddLeg (S Ang Fa Reach A B C T O)
  (bind L Span)
  (bind z (Math|Vector|MakeVector 0.0 0.0 0.0))
  (Utilities|Array|Add HipL (Math|Vector|MakeVector (+ (* (* 0.112 (Math|Trig|Cos(Radians) Ang)) L) (* 0.03 L)) (* (* S 0.096) (* (Math|Trig|Sin(Radians) Ang) L)) (* -0.012 L)))
  (Utilities|Array|Add RestL (Math|Vector|MakeVector (+ (* (* (Math|Trig|Cos(Radians) Fa) Reach) L) (* 0.03 L)) (* (* S (Math|Trig|Sin(Radians) Fa)) (* Reach L)) 0.0))
  (Utilities|Array|Add LA (* A L))
  (Utilities|Array|Add LB (* B L))
  (Utilities|Array|Add LC (* C L))
  (Utilities|Array|Add LT (* T L))
  (Utilities|Array|Add Off O)
  (Utilities|Array|Add LastP 0.0)
  (Utilities|Array|Add SwT 0.0)
  (Utilities|Array|Add SwDur 0.2)
  (Utilities|Array|Add Tuck 0.0)
  (Utilities|Array|Add Swing false)
  (Utilities|Array|Add Foot z)
  (Utilities|Array|Add From z)
  (for k (range 4)
    (Components|InstancedStaticMesh|AddInstance :self Legs :InstanceTransform (Math|Transform|MakeTransform :Location z)))
  (for k (range 3)
    (Components|InstancedStaticMesh|AddInstance :self Knobs :InstanceTransform (Math|Transform|MakeTransform :Location z))))
''')

# (re)build body + legs for the current Span (LEG_CFG from spider.js: ang, fa, reach, a, b, c, t; gait offset per leg)
fn('Build')
dsl('Build', '''
(fn Build ()
  (Utilities|Array|Clear HipL) (Utilities|Array|Clear RestL) (Utilities|Array|Clear Foot) (Utilities|Array|Clear From)
  (Utilities|Array|Clear LA) (Utilities|Array|Clear LB) (Utilities|Array|Clear LC) (Utilities|Array|Clear LT)
  (Utilities|Array|Clear Off) (Utilities|Array|Clear LastP) (Utilities|Array|Clear SwT) (Utilities|Array|Clear SwDur)
  (Utilities|Array|Clear Tuck) (Utilities|Array|Clear Swing)
  (Components|InstancedStaticMesh|ClearInstances :self Legs)
  (Components|InstancedStaticMesh|ClearInstances :self Knobs)
  (AddLeg :S 1.0 :Ang 0.6 :Fa 0.5 :Reach 0.5 :A 0.165 :B 0.185 :C 0.12 :T 0.06 :O 0.18)
  (AddLeg :S 1.0 :Ang 1.1 :Fa 1.08 :Reach 0.44 :A 0.15 :B 0.165 :C 0.11 :T 0.055 :O 0.62)
  (AddLeg :S 1.0 :Ang 1.7 :Fa 1.9 :Reach 0.44 :A 0.145 :B 0.155 :C 0.125 :T 0.055 :O 0.06)
  (AddLeg :S 1.0 :Ang 2.3 :Fa 2.62 :Reach 0.5 :A 0.172 :B 0.182 :C 0.16 :T 0.06 :O 0.5)
  (AddLeg :S -1.0 :Ang 0.6 :Fa 0.5 :Reach 0.5 :A 0.165 :B 0.185 :C 0.12 :T 0.06 :O 0.68)
  (AddLeg :S -1.0 :Ang 1.1 :Fa 1.08 :Reach 0.44 :A 0.15 :B 0.165 :C 0.11 :T 0.055 :O 0.12)
  (AddLeg :S -1.0 :Ang 1.7 :Fa 1.9 :Reach 0.44 :A 0.145 :B 0.155 :C 0.125 :T 0.055 :O 0.56)
  (AddLeg :S -1.0 :Ang 2.3 :Fa 2.62 :Reach 0.5 :A 0.172 :B 0.182 :C 0.16 :T 0.06 :O 0.0)
  (Rendering|Material|SetMaterial :self Body :ElementIndex 0 :Material "/Game/Game/Mat/MI_SpiderBody.MI_SpiderBody")
  (Rendering|Material|SetMaterial :self Abdomen :ElementIndex 0 :Material "/Game/Game/Mat/MI_SpiderAbd.MI_SpiderAbd")
  (Rendering|Material|SetMaterial :self Legs :ElementIndex 0 :Material "/Game/Game/Mat/MI_SpiderLeg.MI_SpiderLeg")
  (Rendering|Material|SetMaterial :self Knobs :ElementIndex 0 :Material "/Game/Game/Mat/MI_SpiderLeg.MI_SpiderLeg")
  (Collision|SetCollisionEnabled :self Body :NewType "NoCollision")
  (Collision|SetCollisionEnabled :self Abdomen :NewType "NoCollision")
  (Collision|SetCollisionEnabled :self Legs :NewType "NoCollision")
  (Collision|SetCollisionEnabled :self Knobs :NewType "NoCollision")
  (Tint)
  (bind L (/ Span 100.0))
  (Transformation|SetRelativeTransform :self Body :NewTransform (Math|Transform|MakeTransform
     :Location (Math|Vector|MakeVector (* 6.0 L) 0.0 (* 1.0 L)) :Scale (Math|Vector|MakeVector (* 0.22 L) (* 0.19 L) (* 0.1 L))))
  (Transformation|SetRelativeTransform :self Abdomen :NewTransform (Math|Transform|MakeTransform
     :Location (Math|Vector|MakeVector (* -17.0 L) 0.0 (* 2.0 L)) :Scale (Math|Vector|MakeVector (* 0.27 L) (* 0.21 L) (* 0.17 L))))
  (bind here (Transformation|GetActorLocation))
  (bind gz (GroundZ :P here))
  (Transformation|SetActorLocationAndRotation :self self
     :NewLocation (Math|Vector|MakeVector (.x here) (.y here) (+ gz (* Span 0.09)))
     :NewRotation (Math|Rotator|MakeRotator 0.0 0.0 Yaw))
  (for i (range 8)
    (bind rw (RestAt :I i :TA 0.0))
    (Utilities|Array|SetArrayElem Foot i rw)
    (SolveLeg :I i)))
''')

# hip -> knee -> ankle analytic 2-bone IK; metatarsus hangs from the ankle, tarsus lies on the ground (spider.js solve())
fn('SolveLeg', [('I', 'int')])
dsl('SolveLeg', '''
(fn SolveLeg (I)
  (bind L Span)
  (bind a (Utilities|Array|Get(acopy) LA I))
  (bind b (Utilities|Array|Get(acopy) LB I))
  (bind c (Utilities|Array|Get(acopy) LC I))
  (bind t (Utilities|Array|Get(acopy) LT I))
  (bind tk (Utilities|Array|Get(acopy) Tuck I))
  (bind foot (Utilities|Array|Get(acopy) Foot I))
  (bind hip (Math|Transform|TransformLocation (Transformation|GetActorTransform) (Utilities|Array|Get(acopy) HipL I)))
  (bind up (Math|Vector|MakeVector 0.0 0.0 1.0))
  (bind out (Math|Vector|Normalize (Math|Vector|MakeVector (- (.x foot) (.x hip)) (- (.y foot) (.y hip)) 0.0)))
  (bind tdir (Math|Vector|Normalize (+ out (* up (- -0.22 (* 0.55 tk))))))
  (bind base (- foot (* tdir t)))
  (bind ad (Math|Vector|Normalize (- (* up (+ 0.55 (* 0.3 tk))) (* out (- 0.83 (* 0.3 tk))))))
  (bind ank0 (+ base (* ad c)))
  (bind dir (Math|Vector|Normalize (- ank0 hip)))
  (bind d (Math|Float|Clamp(Float) (Math|Vector|VectorLength (- ank0 hip)) (+ (Math|Float|Absolute(Float) (- a b)) 0.1) (* (+ a b) 0.998)))
  (bind ankle (+ hip (* dir d)))
  (bind x (/ (+ (- (* a a) (* b b)) (* d d)) (* 2.0 d)))
  (bind y (Math|Float|Sqrt (Math|Float|Max(Float) 0.0 (- (* a a) (* x x)))))
  (bind bend (Math|Vector|Normalize (+ up (* out 0.35))))
  (bind perp (Math|Vector|Normalize (- bend (* dir (Math|Vector|DotProduct bend dir)))))
  (bind knee (+ (+ hip (* dir x)) (* perp y)))
  (bind k (* I 4))
  (Seg :Idx k :A hip :B knee :R (* L 0.017))
  (Seg :Idx (+ k 1) :A knee :B ankle :R (* L 0.015))
  (Seg :Idx (+ k 2) :A ankle :B base :R (* L 0.011))
  (Seg :Idx (+ k 3) :A base :B foot :R (* L 0.009))
  (bind j (* I 3))
  (Knob :Idx j :P knee :R (* L 0.0165))
  (Knob :Idx (+ j 1) :P ankle :R (* L 0.0128))
  (Knob :Idx (+ j 2) :P base :R (* L 0.0092)))
''')

fn('StartSwing', [('I', 'int'), ('Dur', 'float')])
dsl('StartSwing', '''
(fn StartSwing (I Dur)
  (Utilities|Array|SetArrayElem Swing I true)
  (Utilities|Array|SetArrayElem SwT I 0.0)
  (Utilities|Array|SetArrayElem SwDur I (Math|Float|Max(Float) Dur 0.05))
  (Utilities|Array|SetArrayElem From I (Utilities|Array|Get(acopy) Foot I))
  (Variables|Default|SetNSwing (+ NSwing 1)))
''')

# metachronal tetrapod gait (spider.js update): phase-driven swings while walking, settle steps while standing
fn('Gait', [('DT', 'float')])
dsl('Gait', '''
(fn Gait (DT)
  (bind L Span)
  (bind freq (Math|Float|Min(Float) 5.5 (/ (+ Speed (* (Math|Float|Absolute(Float) (Math|Trig|DegreesToRadians YawRate)) (* L 0.45))) (* L 0.24))))
  (bind moving (> freq 0.3))
  (if moving (Variables|Default|SetPhase (+ Phase (* freq DT))))
  (bind duty (Math|Float|Lerp 0.66 0.52 (Math|Float|Clamp(Float) (/ Speed (* L 1.6)) 0.0 1.0)))
  (bind sw (- 1.0 duty))
  (bind lead (select moving (* (/ duty (Math|Float|Max(Float) freq 0.01)) 0.5) 0.0))
  (Variables|Default|SetNSwing 0)
  (for i (range 8)
    (if (Utilities|Array|Get(acopy) Swing i) (Variables|Default|SetNSwing (+ NSwing 1))))
  (for i (range 8)
    (bind restW (RestAt :I i :TA 0.0))
    (if (not (Utilities|Array|Get(acopy) Swing i))
      (bind p (Math|Float|Fraction (+ Phase (Utilities|Array|Get(acopy) Off i))))
      (bind lp (Utilities|Array|Get(acopy) LastP i))
      (bind dist (Math|Vector|Distance2D(Vector) (Utilities|Array|Get(acopy) Foot i) restW))
      (if moving
        (if (and (< p sw) (or (>= lp sw) (> lp p)))
          (StartSwing :I i :Dur (/ sw freq)))
        (else
          (if (and (> dist (* L 0.06)) (< NSwing 2))
            (StartSwing :I i :Dur (Math|Random|RandomFloatinRange 0.17 0.24)))))
      (Utilities|Array|SetArrayElem LastP i p)
      (if (and (not (Utilities|Array|Get(acopy) Swing i)) (> dist (* L 0.34)))
        (StartSwing :I i :Dur 0.1)))
    (if (Utilities|Array|Get(acopy) Swing i)
      (bind st (+ (Utilities|Array|Get(acopy) SwT i) (/ DT (Utilities|Array|Get(acopy) SwDur i))))
      (Utilities|Array|SetArrayElem SwT i st)
      (bind s (Math|Float|Min(Float) st 1.0))
      (bind tgt (RestAt :I i :TA lead))
      (bind from (Utilities|Array|Get(acopy) From i))
      (bind u (Math|Float|Clamp(Float) (/ (- s 0.1) 0.8) 0.0 1.0))
      (bind e (* (* u u) (- 3.0 (* 2.0 u))))
      (bind h (Math|Float|Power (Math|Trig|Sin(Radians) (* 3.14159 (Math|Float|Min(Float) 1.0 (* s 1.08)))) 0.75))
      (bind lift (+ (* L 0.04) (* (Math|Float|Max(Float) 0.0 (- (.z tgt) (.z from))) 0.6)))
      (Utilities|Array|SetArrayElem Foot i (+ (Math|Vector|Lerp(Vector) from tgt e) (Math|Vector|MakeVector 0.0 0.0 (* h lift))))
      (Utilities|Array|SetArrayElem Tuck i h)
      (if (>= s 1.0)
        (bind fv (CamVol :P tgt :Far (+ 6000.0 (* L 2.0))))
        (if (> fv 0.03)
          (Audio|PlaySoundatLocation :Sound "/Game/Game/Sound/S_Step.S_Step" :Location tgt :VolumeMultiplier (* fv (Math|Float|Clamp(Float) (/ L 2500.0) 0.15 0.8))
             :PitchMultiplier (Math|Float|Clamp(Float) (- 1.7 (/ L 2000.0)) 0.45 1.6)))
        (Utilities|Array|SetArrayElem Swing i false)
        (Utilities|Array|SetArrayElem Tuck i 0.0)
        (Utilities|Array|SetArrayElem Foot i tgt)))
    (SolveLeg :I i)))
''')

# wander in stop-and-go bursts around Home (game.js 'wander' + drive()); body height = mean foot height + 0.09 span
fn('Move', [('DT', 'float')])
dsl('Move', '''
(fn Move (DT)
  (bind L Span)
  (bind here (Transformation|GetActorLocation))
  (Variables|Default|SetPauseT (- PauseT DT))
  (Variables|Default|SetBurstT (- BurstT DT))
  (if (and (not Hunting) (or (not HasTarget) (< (Math|Vector|Distance2D(Vector) here Target) (* L 0.4))))
    (bind ang (Math|Random|RandomFloatinRange 0.0 6.2832))
    (bind r (* (Math|Float|Max(Float) WanderRadius (* L 2.5)) (Math|Float|Sqrt (Math|Random|RandomFloat))))
    (bind c (select (>= L 1200.0) (Math|Vector|MakeVector 0.0 0.0 (.z Home)) Home))
    (bind t (+ c (Math|Vector|MakeVector (* r (Math|Trig|Cos(Radians) ang)) (* r (Math|Trig|Sin(Radians) ang)) 0.0)))
    (Variables|Default|SetTarget (Math|Vector|MakeVector (Math|Float|Clamp(Float) (.x t) -5600.0 5600.0) (Math|Float|Clamp(Float) (.y t) -3600.0 3600.0) (.z t)))
    (Variables|Default|SetHasTarget true)
    (Variables|Default|SetPauseT (select Blocked 0.0 (Math|Random|RandomFloatinRange 1.0 4.0)))
    (Variables|Default|SetBlocked false))
  (if (and (<= BurstT 0.0) (not Hunting))
    (Variables|Default|SetBurstT (Math|Random|RandomFloatinRange 1.5 4.0))
    (if (< (Math|Random|RandomFloat) 0.55)
      (Variables|Default|SetPauseT (Math|Random|RandomFloatinRange 0.5 1.8))))
  (if Hunting (Variables|Default|SetPauseT 0.0))
  (bind still (or (or (> PauseT 0.0) (== Stage 2)) Eating))
  (bind dx (- (.x Target) (.x here)))
  (bind dy (- (.y Target) (.y here)))
  (bind dYaw (Math|Rotator|NormalizeAxis (- (Math|Trig|Atan2(Degrees) dy dx) Yaw)))
  (bind wantRate (select still 0.0 (Math|Float|Clamp(Float) (* dYaw 3.5) -160.0 160.0)))
  (Variables|Default|SetYawRate (Math|Float|Lerp YawRate wantRate (Math|Float|Clamp(Float) (* DT 5.0) 0.0 1.0)))
  (Variables|Default|SetYaw (+ Yaw (* YawRate DT)))
  (bind face (Math|Float|Clamp(Float) (/ (- (Math|Trig|Cos(Degrees) dYaw) 0.2) 0.8) 0.0 1.0))
  (bind Lg (/ L 100.0))
  (bind top (* (* (* L 0.6) (Math|Float|Power (/ 9.0 (Math|Float|Max(Float) Lg 9.0)) 0.35)) 0.45))
  (bind dist (Math|Float|Sqrt (+ (* dx dx) (* dy dy))))
  (bind rush (select (and Hunting (< dist (* L 2.2))) 2.2 (select (and Hunting (> ChaseT 0.0)) 1.6 1.0)))
  (bind want (select still 0.0 (* (* (* top face) rush) (Math|Float|Clamp(Float) (/ dist (* L 0.8)) 0.2 1.0))))
  (Variables|Default|SetSpeed (Math|Interpolation|FInterpTo Speed want DT 4.0))
  (bind fwd (Math|Vector|MakeVector (Math|Trig|Cos(Degrees) Yaw) (Math|Trig|Sin(Degrees) Yaw) 0.0))
  (Variables|Default|SetVel (* fwd Speed))
  (bind zs (+ (+ (+ (.z (Utilities|Array|Get(acopy) Foot 0)) (.z (Utilities|Array|Get(acopy) Foot 1))) (+ (.z (Utilities|Array|Get(acopy) Foot 2)) (.z (Utilities|Array|Get(acopy) Foot 3))))
              (+ (+ (.z (Utilities|Array|Get(acopy) Foot 4)) (.z (Utilities|Array|Get(acopy) Foot 5))) (+ (.z (Utilities|Array|Get(acopy) Foot 6)) (.z (Utilities|Array|Get(acopy) Foot 7))))))
  (bind gz (GroundZ :P here))
  (bind zc (+ (* 0.5 (/ zs 8.0)) (* 0.5 gz)))
  (bind nz (Math|Interpolation|FInterpTo (.z here) (+ zc (* L 0.09)) DT 6.0))
  (bind np0 (+ here (* Vel DT)))
  (bind gzn (GroundZ :P (+ np0 (* fwd (* L 0.3)))))
  (bind wall (> (- gzn gz) (* L 0.35)))
  (if (and wall (not Hunting)) (Variables|Default|SetHasTarget false) (Variables|Default|SetBlocked true))
  (if (and wall Hunting) (Variables|Default|SetYaw (+ Yaw (* 150.0 DT))))
  (bind np (select wall here np0))
  (Transformation|SetActorLocationAndRotation :self self
     :NewLocation (Math|Vector|MakeVector (.x np) (.y np) nz)
     :NewRotation (Math|Rotator|MakeRotator 0.0 0.0 Yaw)))
''')


# colour by molt stage: premolt = dark abdomen, molting / soft = pale new skin
fn('Tint')
dsl('Tint', '''
(fn Tint ()
  (if (== Stage 1)
    (Rendering|Material|SetMaterial :self Abdomen :ElementIndex 0 :Material "/Game/Game/Mat/MI_Black.MI_Black")
    (elif (>= Stage 2)
      (Rendering|Material|SetMaterial :self Body :ElementIndex 0 :Material "/Game/Game/Mat/MI_Shell.MI_Shell")
      (Rendering|Material|SetMaterial :self Abdomen :ElementIndex 0 :Material "/Game/Game/Mat/MI_Shell.MI_Shell")
      (Rendering|Material|SetMaterial :self Legs :ElementIndex 0 :Material "/Game/Game/Mat/MI_Shell.MI_Shell")
      (Rendering|Material|SetMaterial :self Knobs :ElementIndex 0 :Material "/Game/Game/Mat/MI_Shell.MI_Shell")
      (else
        (Rendering|Material|SetMaterial :self Body :ElementIndex 0 :Material "/Game/Game/Mat/MI_SpiderBody.MI_SpiderBody")
        (Rendering|Material|SetMaterial :self Abdomen :ElementIndex 0 :Material "/Game/Game/Mat/MI_SpiderAbd.MI_SpiderAbd")
        (Rendering|Material|SetMaterial :self Legs :ElementIndex 0 :Material "/Game/Game/Mat/MI_SpiderLeg.MI_SpiderLeg")
        (Rendering|Material|SetMaterial :self Knobs :ElementIndex 0 :Material "/Game/Game/Mat/MI_SpiderLeg.MI_SpiderLeg")))))
''')

# needs (game.js): 1 real s = 0.5 game hour x TimeScale; hunger +1.3/h (not while molting); growth 100 -> premolt 30 h -> molting 6 h -> soft 48 h
fn('Needs', [('DT', 'float')])
dsl('Needs', '''
(fn Needs (DT)
  (bind hrs (* (* DT 0.5) TimeScale))
  (if (!= Stage 2) (Variables|Default|SetHunger (Math|Float|Clamp(Float) (+ Hunger (* hrs 1.3)) 0.0 100.0)))
  (Variables|Default|SetStageT (+ StageT hrs))
  (if (and (== Stage 0) (>= Growth 100.0))
    (Variables|Default|SetStage 1) (Variables|Default|SetStageT 0.0)
    (Tint))
  (if (and (== Stage 1) (> StageT 30.0))
    (Variables|Default|SetStage 2) (Variables|Default|SetStageT 0.0)
    (Tint))
  (if (and (== Stage 2) (> StageT 6.0))
    (Variables|Default|SetSpan (Math|Float|Min(Float) MaxSpan (* Span 1.35)))
    (Variables|Default|SetMolts (+ Molts 1))
    (Variables|Default|SetGrowth 0.0)
    (Variables|Default|SetStage 3) (Variables|Default|SetStageT 0.0)
    (Build)
    (Tint))
  (if (and (== Stage 3) (> StageT 48.0))
    (Variables|Default|SetStage 0) (Variables|Default|SetStageT 0.0)
    (Tint)))
''')

# eat: game.js hunger -= value*1.4, growth += value*12/span(game units); refused in premolt/molting/soft
fn('Feed', [('Value', 'float')], [('Ate', 'bool')])
dsl('Feed', '''
(fn Feed (Value)
  (if (!= Stage 0) (return false))
  (Variables|Default|SetHunger (Math|Float|Clamp(Float) (- Hunger (* Value 1.4)) 0.0 100.0))
  (Variables|Default|SetGrowth (Math|Float|Clamp(Float) (+ Growth (/ (* Value 12.0) (/ Span 100.0))) 0.0 100.0))
  (return true))
''')

# hunting (game.js): feels prey vibration within a radius (moving prey felt further), stalks, rushes, grabs at fang reach,
# eats for a while (prey held at the fangs, kicking), then Feed(value). Only in the normal stage (premolt/molting/soft refuse food).
fn('Hunt', [('DT', 'float')])
dsl('Hunt', '''
(fn Hunt (DT)
  (bind L Span)
  (bind here (Transformation|GetActorLocation))
  (Variables|Default|SetIgnoreT (- IgnoreT DT))
  (Variables|Default|SetDTm DT)
  (if Eating
    (if (< (Math|Float|%(Float) EatT 0.9) DT)
      (Audio|PlaySoundatLocation :Sound "/Game/Game/Sound/S_Crunch.S_Crunch" :Location here :VolumeMultiplier (* 0.6 (CamVol :P here :Far 9000.0))))
    (Variables|Default|SetEatT (- EatT DT))
    (bind fwd (Math|Vector|MakeVector (Math|Trig|Cos(Degrees) Yaw) (Math|Trig|Sin(Degrees) Yaw) 0.0))
    (bind at (+ (+ here (* fwd (* L 0.2))) (Math|Vector|MakeVector 0.0 0.0 (* L -0.02))))
    (if EatHuman
      (Utilities|IsValid Victim
        (:"Is Valid"
          (Transformation|SetActorLocationAndRotation :self Victim :NewLocation (- at (Math|Vector|MakeVector 0.0 0.0 90.0))
             :NewRotation (Math|Rotator|MakeRotator 0.0 70.0 (+ Yaw 180.0)))
          (if (<= EatT 0.0)
            (bind ate (Feed :Value 16.0))
            (Actor|DestroyActor :self Victim)
            (Variables|Default|SetEating false)
            (Variables|Default|SetEatHuman false)
            (Variables|Default|SetMeals (+ Meals 1))
            (Variables|Default|SetPauseT (Math|Random|RandomFloatinRange 4.0 8.0))))
        (:"Is Not Valid" (Variables|Default|SetEating false)))
      (else
        (Utilities|IsValid Prey
          (:"Is Valid"
            (Transformation|SetActorLocationAndRotation :self Prey :NewLocation at
               :NewRotation (Math|Rotator|MakeRotator 0.0 25.0 (+ Yaw 180.0)))
            (if (<= EatT 0.0)
              (bind v (Class|BPPrey|GetValue :self Prey))
              (bind ate2 (Feed :Value v))
              (Actor|DestroyActor :self Prey)
              (Variables|Default|SetEating false)
              (Variables|Default|SetMeals (+ Meals 1))
              (Variables|Default|SetPauseT (Math|Random|RandomFloatinRange 2.0 5.0))))
          (:"Is Not Valid"
            (Variables|Default|SetEating false)))))
    (else (Seek))))
''')

fn('Seek')
dsl('Seek', '''
(fn Seek ()
  (bind L Span)
  (bind here (Transformation|GetActorLocation))
  (Variables|Default|SetHunting false)
  (if (or (!= Stage 0) (< Hunger 12.0)) (return))
  (bind all (Actor|GetAllActorsOfClass :ActorClass "/Game/Game/BP_Prey.BP_Prey_C"))
  (Variables|Default|SetBest 1000000.0)
  (for a all
    (bind p (Transformation|GetActorLocation :self a))
    (bind d (Math|Vector|Distance2D(Vector) here p))
    (bind moving (> (Class|BPPrey|GetSpeed :self a) 5.0))
    (bind sense (+ (* L (select moving 3.2 1.4)) (select moving 900.0 300.0)))
    (if (and (< d sense) (< d Best))
      (Variables|Default|SetPrey a)
      (Variables|Default|SetBest d)))
  (if (and (>= Best 999999.0) (and (>= L 1200.0) (and (> Hunger 28.0) (<= IgnoreT 0.0))))
    (Variables|Default|SetBestH 1000000.0)
    (for h (Actor|GetAllActorsOfClass :ActorClass "/Game/Game/BP_Human.BP_Human_C")
      (bind hp (Transformation|GetActorLocation :self h))
      (bind hs (Class|BPHuman|GetSpeed :self h))
      (bind vib (select (> hs 600.0) 1.5 (select (> hs 200.0) 1.0 (select (> hs 20.0) 0.6 0.22))))
      (bind r (/ (Math|Vector|Distance2D(Vector) here hp) (* (+ 2500.0 (* L 1.0)) vib)))
      (if (and (< r 1.0) (and (< r BestH) (not (Class|BPHuman|GetBoarded :self h))))
        (Variables|Default|SetVictim h)
        (Variables|Default|SetBestH r))))
  (bind vv (Valid :A Victim))
  (if (and (>= Best 999999.0) (and (< BestH 1.0) vv))
    (Variables|Default|SetHunting true)
    (Variables|Default|SetHasTarget true)
    (bind vp (Transformation|GetActorLocation :self Victim))
    (Variables|Default|SetTarget vp)
    (Variables|Default|SetChaseT (+ ChaseT DTm))
    (if (> ChaseT 12.0)
      (Variables|Default|SetHunting false)
      (Variables|Default|SetChaseT 0.0)
      (Variables|Default|SetIgnoreT 8.0)
      (Variables|Default|SetPauseT 3.0))
    (if (< (Math|Vector|Distance2D(Vector) here vp) (* L 0.4))
      (Variables|Default|SetEating true)
      (Variables|Default|SetEatHuman true)
      (Variables|Default|SetHunting false)
      (Variables|Default|SetChaseT 0.0)
      (Variables|Default|SetEatT 10.0)
      (Class|BPHuman|SetHeld :self Victim :Held true)))
  (if (>= BestH 1.0) (Variables|Default|SetChaseT 0.0))
  (Variables|Default|SetBestH 1000000.0)
  (if (< Best 999999.0)
    (Variables|Default|SetHunting true)
    (Variables|Default|SetHasTarget true)
    (bind pp (Transformation|GetActorLocation :self Prey))
    (Variables|Default|SetTarget pp)
    (if (< Best (* L 0.42))
      (Variables|Default|SetEating true)
      (Variables|Default|SetHunting false)
      (Variables|Default|SetEatT (Math|Random|RandomFloatinRange 6.0 10.0))
      (Class|BPPrey|SetHeld :self Prey :Held true)
      (Variables|Default|SetChaseT 0.0))))
''')

dsl('EventGraph', '''
(event EventBeginPlay
  (Variables|Default|SetBestH 1000000.0)
  (Variables|Default|SetNoWalk (Actor|GetAllActorswithTag :Tag "NoWalk"))
  (Variables|Default|SetHome (Transformation|GetActorLocation))
  (Variables|Default|SetYaw (.yaw (Transformation|GetActorRotation)))
  (Build))
(event EventTick (DeltaSeconds)
  (bind dt (Math|Float|Min(Float) DeltaSeconds 0.05))
  (Needs :DT dt)
  (Hunt :DT dt)
  (Move :DT dt)
  (Gait :DT dt))
''')
compile()
